package com.yqjr.fin.risk.stat.mapper;

import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.risk.stat.entity.ScheduleLog;

import java.util.Map;

public interface ScheduleLogMapper extends Mapper<ScheduleLog, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
    public void custom_r0401003(Map<String, Object> paramMap);
	
}
