package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/personMain")
public class PersonMainController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/personmain/personMainList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/personmain/personMainView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/personmain/personMainForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/personmain/personMainModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/personmain/personMainModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/personmain/personMainListModal";
	}

	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
	@RequestMapping(value = "/attach")
	public String attach() {

		return "framework/system/personintegrate/personInTeGrateList";
	}

	@RequestMapping(value = "/tab")
	public String tab() {
		return "framework/system/personintegrate/personInTeGrateModify";
	}

	@RequestMapping(value = "/tabview")
	public String tabview() {
		return "framework/system/personintegrate/personInTeGrateView";
	}
}