package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.entity.ActiveDealer;
import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.ActiveCar;
import com.yqjr.fin.mkmm.sales.mapper.ActiveCarMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class ActiveCarService extends BaseService<ActiveCarMapper, ActiveCar, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
    @Autowired
    private ActiveCarMapper activeCarMapper;

    /**
     * 根据code查活动车辆
     * create by fanna 20180604
     * @return
     */
    public List<ActiveCar> selectActiveCarByCode(String activeCode,String company){

        return activeCarMapper.selectActiveCarByCode(activeCode,company);
    }

    public void patchByActiveCode(ActiveCar activeCar) {
        activeCarMapper.patchByActiveCode(activeCar);
    }
}