package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.entity.ActiveMain;
import com.yqjr.fin.mkmm.sales.mapper.ActiveMainMapper;
import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.ActiveMatchTask;
import com.yqjr.fin.mkmm.sales.mapper.ActiveMatchTaskMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class ActiveMatchTaskService extends BaseService<ActiveMatchTaskMapper, ActiveMatchTask, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion

    @Autowired
    private ActiveMatchTaskMapper activeMatchTaskMapper;

    public int insertBatch(List<ActiveMatchTask> list){
        return activeMatchTaskMapper.insertBatch(list);
    }

    public int insertOne(ActiveMatchTask activeMatchTask){
        return activeMatchTaskMapper.insert(activeMatchTask);
    }

    public List<ActiveMatchTask> selectActiveMatchMain(ActiveMatchTask activeMatchTask){
        return activeMatchTaskMapper.selectActiveMatchMain(activeMatchTask);
    }

}