package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.ActiveProd;
import com.yqjr.fin.mkmm.sales.mapper.ActiveProdMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class ActiveProdService extends BaseService<ActiveProdMapper, ActiveProd, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
    @Autowired
    private ActiveProdMapper activeProdMapper;

    /**
     * 根据code查活动产品
     * create by fanna 20180604
     * @return
     */
    public List<ActiveProd> selectActiveProdByCode(String activeCode,String company){

        return activeProdMapper.selectActiveProdByCode(activeCode,company);
    }

    public void deleteByActiveCode(String activeCode) {
        activeProdMapper.deleteByActiveCode(activeCode);
    }
}