package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.condition.EventPersonCondition;
import com.yqjr.fin.mkmm.sales.entity.PersonTeam;
import com.yqjr.scfw.common.pagination.model.PageBounds;
import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.EventPerson;
import com.yqjr.fin.mkmm.sales.mapper.EventPersonMapper;
import org.apache.poi.ss.formula.functions.Even;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class EventPersonService extends BaseService<EventPersonMapper, EventPerson, Long> {

    @Autowired
    private EventPersonMapper eventPersonMapper;
    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
    public List<EventPerson> selectT(EventPersonCondition eventPersonCondition){
        return eventPersonMapper.selectT(eventPersonCondition);
    }

    /**
     * 模糊查询人员重大事件
     */
    public List<EventPerson> queryEventPerson(EventPersonCondition eventPersonCondition, PageBounds... pageBounds){
        List<EventPerson> eventPeople =null;
        eventPeople=eventPersonMapper.queryEventPerson(eventPersonCondition,pageBounds);
        return eventPeople;
    }




}