package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.mapper.PersonCityMapper;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.PersonCity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional(readOnly = true)
public class PersonCityService extends BaseService<PersonCityMapper, PersonCity, Long> {
    @Autowired
    private PersonCityMapper personCityMapper;
    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    /**
     * 根据人员代码更新人员城市表
     * @return
     */
    public int patchByPersonCode(PersonCity personCity){
        return personCityMapper.patchByPersonCode(personCity);
    }
    //endregion
}