package com.yqjr.fin.risk.stat.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.risk.stat.entity.A11Dealerdata1;
import com.yqjr.fin.risk.stat.mapper.A11Dealerdata1Mapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional(readOnly = true)
public class A11Dealerdata1Service extends BaseService<A11Dealerdata1Mapper, A11Dealerdata1, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}