package com.yqjr.fin.cvc.core.dao;

import tk.mybatis.mapper.common.Mapper;
import com.yqjr.fin.cvc.core.entity.TkApplybasic;

public interface TkApplybasicDao extends Mapper<TkApplybasic> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
	
}
