package com.yqjr.fin.risk.stat.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.risk.stat.entity.FctAltArea;
import com.yqjr.fin.risk.stat.mapper.FctAltAreaMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional(readOnly = true)
public class FctAltAreaService extends BaseService<FctAltAreaMapper, FctAltArea, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}