package com.yqjr.fin.cvc.core.bizz;

import com.ritoinfo.framework.evo.sp.base.starter.assist.BaseHelper;
import com.ritoinfo.framework.evo.sp.base.starter.bizz.BaseMapperBizz;
import com.yqjr.fin.cvc.core.dto.TempTabale1Dto;
import com.yqjr.fin.cvc.core.dao.TempTabale1Dao;
import com.yqjr.fin.cvc.core.entity.TempTabale1;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Transactional(readOnly = true)
@Service
public class TempTabale1Bizz extends BaseMapperBizz<TempTabale1Dao, TempTabale1, Long,TempTabale1Dto> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
    public TempTabale1Dto getTestId(Long id) {
        return toDto(dao.getTestId(id));
    }

}