package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.TeamMainCondition;
import com.yqjr.fin.mkmm.sales.entity.TeamReview;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonTeamVo;
import com.yqjr.scfw.common.condition.BaseCondition;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.TeamMain;
import com.yqjr.scfw.common.pagination.model.PageBounds;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TeamMainMapper extends Mapper<TeamMain, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    int patchByTeamCode(TeamMain teamMain);

    /**
     * 模糊查询
     * @param teamMainCondition
     * @return
     */
    List<TeamMain> queryTeamMainList(TeamMainCondition teamMainCondition);

    //综合查询，团队下人员信息
    List<PersonTeamVo> queryPersonByTeamCode(String teamCode,String company);

    //模糊查询团队维护列表
    List<TeamMain> queryTeamMain(TeamMainCondition teamMainCondition, PageBounds... pageBounds);




    //模糊查询综合查询列表
    List<TeamMain> queryAllListTeamMain(TeamMainCondition teamMainCondition, PageBounds... pageBounds);


    TeamReview selectBySearchId(@Param("id") Long id);

    List<TeamMain> selectAllTeamStatus();
    public List<TeamMain> selectByCode(String teamCode);

    /**
     * 根据名称查数量
     * @param teamMainCondition
     * @return
     */
    int selectTeamCount(TeamMainCondition teamMainCondition);

}
