package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeProdReview")
public class ActiveProdReviewController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activeprodreview/activeProdReviewList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activeprodreview/activeProdReviewView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activeprodreview/activeProdReviewForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activeprodreview/activeProdReviewModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activeprodreview/activeProdReviewModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activeprodreview/activeProdReviewListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}