package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeArea")
public class ActiveAreaController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activearea/activeAreaList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activearea/activeAreaView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activearea/activeAreaForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activearea/activeAreaModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activearea/activeAreaModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activearea/activeAreaListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}