package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/personCity")
public class PersonCityController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/personcity/personCityList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/personcity/personCityView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/personcity/personCityForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/personcity/personCityModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/personcity/personCityModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/personcity/personCityListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}