package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.ActiveDealer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ActiveDealerMapper extends Mapper<ActiveDealer, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    /**
     * 根据code查活动经销商
     * create by fanna 20180604
     * @return
     */
    List<ActiveDealer> selectActiveDealeByCode(String areaCode,String company);

    void deleteByActiveCode(@Param("activeCode") String activeCode);
}
