package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/personTeam")
public class PersonTeamController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/personteam/personTeamList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/personteam/personTeamView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/personteam/personTeamForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/personteam/personTeamModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/personteam/personTeamModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/personteam/personTeamListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}