package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeAddition")
public class ActiveAdditionController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activeaddition/activeAdditionList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activeaddition/activeAdditionView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activeaddition/activeAdditionForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activeaddition/activeAdditionModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activeaddition/activeAdditionModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activeaddition/activeAdditionListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}