package com.yqjr.fin.pvc.core.dao;

import com.yqjr.fin.pvc.core.dto.TempTabale1Dto;
import tk.mybatis.mapper.common.Mapper;
import com.yqjr.fin.pvc.core.entity.TempTabale1;

import java.util.List;

public interface TempTabale1Dao extends Mapper<TempTabale1> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    TempTabale1 getTestId(Long id);
	
}
