package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.mapper.PersonMainHisMapper;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonMainVo;
import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.PersonMainHis;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional(readOnly = true)
public class PersonMainHisService extends BaseService<PersonMainHisMapper, PersonMainHis, Long> {

    @Autowired
     private PersonMainHisMapper personMainHisMapper;


     public PersonMainVo selectPersonMainById(long id){
         PersonMainVo personMainVo=personMainHisMapper.selectPersonMainVoById(id);
         return  personMainVo;
     }

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}