package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.PlanTrackYear;
import com.yqjr.fin.mkmm.sales.mapper.PlanTrackYearMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class PlanTrackYearService extends BaseService<PlanTrackYearMapper, PlanTrackYear, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion

    @Autowired
    private PlanTrackYearMapper planTrackYearMapper;

    //当前月数据数据进入轨迹表
    public List<PlanTrackYear> selectPlanTrackYear(String year,String company){
        return planTrackYearMapper.selectPlanTrackYear(year,company);
    }

    //根据年删除数据
    public void deletePlanTrackYear(String year,String company){
        planTrackYearMapper.deletePlanTrackYear(year,company);
    }
}