package com.yqjr.fin.mkmm.sales.entity;

import com.alibaba.fastjson.annotation.JSONField;
import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;
import java.math.BigDecimal;

public class ActiveMatchMain extends BaseEntity<ActiveMatchMain> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/activeMatchMain/list
     *表单维护路径：/activeMatchMain/form
     *
     */

    /**
     * ID
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 结算单号
     */
    @Length(min = 0, max = 20)
    private String billNo;

    /**
     * 统计类型 (01-活动统计)
     */
    @Length(min = 0, max = 20)
    private String countType;

    /**
     * 业务代码
     */
    @Length(min = 0, max = 20)
    private String businessCode;

    /**
     * 业务名称
     */
    @Length(min = 0, max = 64)
    private String businessName;

    /**
     * 所属公司
     */
    @Length(min = 0, max = 20)
    private String company;

    /**
     * 有效状态
     */
    @Length(min = 0, max = 10)
    private String validStatus;

    /**
     * 结算单上限金额
     */
    @Digits(fraction =14,integer=2)
    private BigDecimal maxBillFee;

    /**
     * 实际活动成交数量
     */
    @Digits(fraction =22,integer=0)
    private Long actualTurnoverCount;

    /**
     * 预计活动成交数量
     */
    @Digits(fraction =22,integer=0)
    private Long estimateTurnoverCount;

    /**
     * 促销活动激励标准
     */
    @Digits(fraction =14,integer=2)
    private BigDecimal avtiveCriterion;

    /**
     * 审核表ID
     */
    @Digits(fraction =22,integer=0)
    private Long feeMainReviewId;

    /**
     * 费用申请归属部门
     */
    @Length(min = 0, max = 20)
    private String feeowner;

    /**
     * 达成率
     */
    @Length(min = 0, max = 20)
    private String reachRate;

    /**
     * 区域代码
     */
    @Length(min = 0, max = 500)
    private String areaCode;

    /**
     * 区域名称
     */
    @Length(min = 0, max = 1000)
    private String areaName;

    /**
     * 品牌编码
     */
    @Length(min = 0, max = 50)
    private String brandsCode;

    /**
     * 品牌名称
     */
    @Length(min = 0, max = 50)
    private String brandsName;

    /**
     * 活动开始日期
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date activeStartime;

    /**
     * 活动截止日期
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date activeEndtime;

    /**
     * 是否发起结算
     */
    @Length(min = 0, max = 20)
    private String isSettlement;

    /**
     * 备注
     */
    @Length(min = 0, max = 500)
    private String remark;

    /**
     * 创建时间
     */
    @JSONField(format="yyyy-MM-dd HH-mm-ss")
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    @JSONField(format="yyyy-MM-dd HH-mm-ss")
    private java.util.Date modifyTime;

    /**
     * 生效时间
     */
    @JSONField(format="yyyy-MM-dd HH-mm-ss")
    private java.util.Date startTime;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 有效标识（如表记录不删除，以此区分,0无效，1有效）
     */
    @Length(min = 0, max = 10)
    private String flag;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBillNo() {
        return billNo;
    }

    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    public String getCountType() {
        return this.countType;
    }

    public void setCountType(String countType) {
        this.countType = countType;
    }

    public String getBusinessCode() {
        return this.businessCode;
    }

    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    public String getBusinessName() {
        return this.businessName;
    }

    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getValidStatus() {
        return this.validStatus;
    }

    public void setValidStatus(String validStatus) {
        this.validStatus = validStatus;
    }

    public BigDecimal getMaxBillFee() { return maxBillFee; }

    public void setMaxBillFee(BigDecimal maxBillFee) {
        this.maxBillFee = maxBillFee;
    }

    public BigDecimal getAvtiveCriterion() {
        return avtiveCriterion;
    }

    public void setAvtiveCriterion(BigDecimal avtiveCriterion) {
        this.avtiveCriterion = avtiveCriterion;
    }

    public Long getActualTurnoverCount() {
        return this.actualTurnoverCount;
    }

    public void setActualTurnoverCount(Long actualTurnoverCount) {
        this.actualTurnoverCount = actualTurnoverCount;
    }

    public Long getEstimateTurnoverCount() {
        return this.estimateTurnoverCount;
    }

    public void setEstimateTurnoverCount(Long estimateTurnoverCount) { this.estimateTurnoverCount = estimateTurnoverCount; }

    public Long getFeeMainReviewId() {
        return this.feeMainReviewId;
    }

    public void setFeeMainReviewId(Long feeMainReviewId) {
        this.feeMainReviewId = feeMainReviewId;
    }

    public String getFeeowner() {
        return this.feeowner;
    }

    public void setFeeowner(String feeowner) {
        this.feeowner = feeowner;
    }

    public String getReachRate() {
        return this.reachRate;
    }

    public void setReachRate(String reachRate) {
        this.reachRate = reachRate;
    }

    public String getAreaCode() {
        return this.areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getAreaName() {
        return this.areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getBrandsCode() {
        return this.brandsCode;
    }

    public void setBrandsCode(String brandsCode) {
        this.brandsCode = brandsCode;
    }

    public String getBrandsName() {
        return this.brandsName;
    }

    public void setBrandsName(String brandsName) {
        this.brandsName = brandsName;
    }

    public java.util.Date getActiveStartime() {
        return this.activeStartime;
    }

    public void setActiveStartime(java.util.Date activeStartime) {
        this.activeStartime = activeStartime;
    }

    public java.util.Date getActiveEndtime() {
        return this.activeEndtime;
    }

    public void setActiveEndtime(java.util.Date activeEndtime) {
        this.activeEndtime = activeEndtime;
    }

    public String getIsSettlement() {
        return this.isSettlement;
    }

    public void setIsSettlement(String isSettlement) {
        this.isSettlement = isSettlement;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public java.util.Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
