package com.yqjr.fin.mkmm.sales.entity;

import com.alibaba.fastjson.annotation.JSONField;
import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;

public class EventPerson extends BaseEntity<EventPerson> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/eventPerson/list
     *表单维护路径：/eventPerson/form
     *
     */

    /**
     * 事件序号
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 事件编号
     */
    @Length(min = 0, max = 12)
    private java.lang.String eventCode;

    /**
     * 事件年度
     */
    @Length(min = 0, max = 18)
    private java.lang.String eventYear;

    /**
     * 受理单位
     */
    @Length(min = 0, max = 20)
    private java.lang.String eventApart;

    /**
     * 事件内容
     */
    @Length(min = 0, max = 530)
    private java.lang.String brandsText;

    /**
     * 事件状态
     */
    @Length(min = 0, max = 128)
    private java.lang.String eventStatus;

    /**
     * 创建时间
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private java.util.Date createTime;

    /**
     * 备注
     */
    @Length(min = 0, max = 256)
    private java.lang.String bemark;

    /**
     * 事项分类
     */
    @Length(min = 0, max = 10)
    private java.lang.String transcode1;

    /**
     * 备注2
     */
    @Length(min = 0, max = 256)
    private java.lang.String transcode2;

    /**
     * 备注3
     */
    @Length(min = 0, max = 256)
    private java.lang.String transcode3;

    /**
     * 备注4
     */
    @Length(min = 0, max = 256)
    private java.lang.String transcode4;

    /**
     * 修改时间
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private java.util.Date modifyTime;

    /**
     * 生效时间
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private java.util.Date startTime;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 最新标识
     */
    @Length(min = 0, max = 256)
    private java.lang.String flag;

    /**
     * 事件归属编号(人员，团队编号)
     */
    @Length(min = 0, max = 50)
    private java.lang.String personCode;

    /**
     * 人员姓名
     */
    @Length(min = 0, max = 50)
    private java.lang.String personName;

    /**
     * 所属公司
     */
    @Length(min = 0, max = 20)
    private java.lang.String company;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.lang.String getEventCode() {
        return this.eventCode;
    }

    public void setEventCode(java.lang.String eventCode) {
        this.eventCode = eventCode;
    }

    public java.lang.String getEventYear() {
        return this.eventYear;
    }

    public void setEventYear(java.lang.String eventYear) {
        this.eventYear = eventYear;
    }

    public java.lang.String getEventApart() {
        return this.eventApart;
    }

    public void setEventApart(java.lang.String eventApart) {
        this.eventApart = eventApart;
    }

    public java.lang.String getBrandsText() {
        return this.brandsText;
    }

    public void setBrandsText(java.lang.String brandsText) {
        this.brandsText = brandsText;
    }

    public java.lang.String getEventStatus() {
        return this.eventStatus;
    }

    public void setEventStatus(java.lang.String eventStatus) {
        this.eventStatus = eventStatus;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.lang.String getBemark() {
        return this.bemark;
    }

    public void setBemark(java.lang.String bemark) {
        this.bemark = bemark;
    }

    public java.lang.String getTranscode1() {
        return this.transcode1;
    }

    public void setTranscode1(java.lang.String transcode1) {
        this.transcode1 = transcode1;
    }

    public java.lang.String getTranscode2() {
        return this.transcode2;
    }

    public void setTranscode2(java.lang.String transcode2) {
        this.transcode2 = transcode2;
    }

    public java.lang.String getTranscode3() {
        return this.transcode3;
    }

    public void setTranscode3(java.lang.String transcode3) {
        this.transcode3 = transcode3;
    }

    public java.lang.String getTranscode4() {
        return this.transcode4;
    }

    public void setTranscode4(java.lang.String transcode4) {
        this.transcode4 = transcode4;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public java.util.Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public java.lang.String getFlag() {
        return this.flag;
    }

    public void setFlag(java.lang.String flag) {
        this.flag = flag;
    }

    public java.lang.String getPersonCode() {
        return this.personCode;
    }

    public void setPersonCode(java.lang.String personCode) {
        this.personCode = personCode;
    }

    public java.lang.String getPersonName() {
        return this.personName;
    }

    public void setPersonName(java.lang.String personName) {
        this.personName = personName;
    }
    public java.lang.String getCompany() {
        return this.company;
    }

    public void setCompany(java.lang.String company) {
        this.company = company;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
