package com.yqjr.fin.mkmm.sales.entity;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;

public class PersonBrank extends BaseEntity<PersonBrank> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/personBrank/list
     *表单维护路径：/personBrank/form
     *
     */

    /**
     * 序列
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 人员代码
     */
    @Length(min = 0, max = 32)
    private java.lang.String personCode;

    /**
     * 城市名称
     */
    @Length(min = 0, max = 32)
    private java.lang.String brandCode;

    /**
     * 城市编号
     */
    @Length(min = 0, max = 128)
    private java.lang.String brandName;

    /**
     * 生效时间
     */
    private java.util.Date startTime;

    /**
     * 创建时间
     */
    private java.util.Date createTime2;

    /**
     * 修改时间
     */
    private java.util.Date modifyTime;

    /**
     * 创建人
     */
    @Digits(fraction =32,integer=0)
    private Long creator2;

    /**
     * 修改人
     */
    @Digits(fraction =32,integer=0)
    private Long modifier;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.lang.String getPersonCode() {
        return this.personCode;
    }

    public void setPersonCode(java.lang.String personCode) {
        this.personCode = personCode;
    }

    public java.lang.String getBrandCode() {
        return this.brandCode;
    }

    public void setBrandCode(java.lang.String brandCode) {
        this.brandCode = brandCode;
    }

    public java.lang.String getBrandName() {
        return this.brandName;
    }

    public void setBrandName(java.lang.String brandName) {
        this.brandName = brandName;
    }

    public java.util.Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getCreateTime2() {
        return this.createTime2;
    }

    public void setCreateTime2(java.util.Date createTime2) {
        this.createTime2 = createTime2;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getCreator2() {
        return this.creator2;
    }

    public void setCreator2(Long creator2) {
        this.creator2 = creator2;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
