management:
  security:
    enabled: false
server:
  port: 50111
spring:
  application:
    name: fin-scfw-config
  profiles:
    active: native
  cloud:
    config:
        native:
          search-locations: classpath:/properties/
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:50101/eureka


