package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeProd")
public class ActiveProdController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activeprod/activeProdList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activeprod/activeProdView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activeprod/activeProdForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activeprod/activeProdModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activeprod/activeProdModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activeprod/activeProdListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}