package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeAdditionHis")
public class ActiveAdditionHisController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activeadditionhis/activeAdditionHisList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activeadditionhis/activeAdditionHisView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activeadditionhis/activeAdditionHisForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activeadditionhis/activeAdditionHisModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activeadditionhis/activeAdditionHisModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activeadditionhis/activeAdditionHisListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}