package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/feeDetail")
public class FeeDetailController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/feedetail/feeDetailList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/feedetail/feeDetailView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/feedetail/feeDetailForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/feedetail/feeDetailModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/feedetail/feeDetailModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/feedetail/feeDetailListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}