package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/personSaleHis")
public class PersonSaleHisController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/personsalehis/personSaleHisList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/personsalehis/personSaleHisView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/personsalehis/personSaleHisForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/personsalehis/personSaleHisModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/personsalehis/personSaleHisModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/personsalehis/personSaleHisListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}