package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/teamMainAttach")
public class TeamMainAttachController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/teammainattach/teamMainList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/teammainattach/teamMainView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/teammainattach/teamMainForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/teammainattach/teamMainModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/teammainattach/teamMainModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/teammainattach/teamMainListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}