package com.yqjr.fin.risk.stat.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.risk.stat.entity.ScheduleLog;
import com.yqjr.fin.risk.stat.mapper.ScheduleLogMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional(readOnly = true)
public class ScheduleLogService extends BaseService<ScheduleLogMapper, ScheduleLog, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}