
package com.yqjr.fin.scfw.meta.condition;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Digits;

import com.yqjr.scfw.common.condition.BaseCondition;

import com.yqjr.fin.scfw.meta.entity.DictItem;

public class DictItemCondition extends BaseCondition<DictItem, Long> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/dictItem/list
     *表单维护路径：/dictItem/form
     *
     */

    /**
     * 主键
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 字典项名称
     */
    @Length(min = 0, max = 30)
    private java.lang.String name;

    /**
     * 字典项值
     */
    @Length(min = 0, max = 16)
    private java.lang.String value;

    /**
     * 状态
     */
    private java.lang.String status;

    /**
     * 顺序
     */
    @Digits(fraction =3,integer=0)
    private Integer gradation;

    /**
     * 字典表ID
     */
    @Digits(fraction =3,integer=0)
    private Integer dictId;

    /**
     * 父ID，对应本表父字典项ID
     */
    @Length(min = 0, max = 64)
    private java.lang.String parentId;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 创建时间
     */
    private java.lang.String createTime;

    /**
     * 最后更新人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 最后更新时间
     */
    private java.lang.String modifyTime;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getValue() {
        return this.value;
    }

    public void setValue(java.lang.String value) {
        this.value = value;
    }

    public java.lang.String getStatus() {
        return this.status;
    }

    public void setStatus(java.lang.String status) {
        this.status = status;
    }

    public Integer getGradation() {
        return this.gradation;
    }

    public void setGradation(Integer gradation) {
        this.gradation = gradation;
    }

    public Integer getDictId() {
        return this.dictId;
    }

    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }

    public java.lang.String getParentId() {
        return this.parentId;
    }

    public void setParentId(java.lang.String parentId) {
        this.parentId = parentId;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public java.lang.String getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.lang.String createTime) {
        this.createTime = createTime;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public java.lang.String getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.lang.String modifyTime) {
        this.modifyTime = modifyTime;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}