
package com.yqjr.fin.scfw.meta.condition;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Digits;

import com.yqjr.scfw.common.condition.BaseCondition;

import com.yqjr.fin.scfw.meta.entity.User;

public class UserCondition extends BaseCondition<User, Long> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/user/list
     *表单维护路径：/user/form
     *
     */

    /**
     * 主键
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 登陆名，英文，唯一
     */
    @Length(min = 0, max = 50)
    private java.lang.String loginName;

    /**
     * 密码，md5加密后密文
     */
    @Length(min = 0, max = 50)
    private java.lang.String loginPassword;

    /**
     * 用户名称，中文
     */
    @Length(min = 0, max = 50)
    private java.lang.String userName;

    /**
     * OA员工编号
     */
    @Length(min = 0, max = 50)
    private java.lang.String oaFdno;

    /**
     * 合同所属公司:见数据字典:comcode
     */
    private java.lang.String comCode;

    /**
     * 所属机构
     */
    @Length(min = 0, max = 30)
    private java.lang.String organizationNo;

    /**
     * 首次登记日期
     */
    private java.lang.String registDate;

    /**
     * 首次等级人登陆名
     */
    @Length(min = 0, max = 50)
    private java.lang.String registUser;

    /**
     * 性别:见数据字典:sex
     */
    private java.lang.String sex;

    /**
     * 手机
     */
    @Length(min = 0, max = 30)
    private java.lang.String mobile;

    /**
     * 邮箱
     */
    @Length(min = 0, max = 50)
    private java.lang.String email;

    /**
     * 微信OPEN_ID
     */
    @Length(min = 0, max = 50)
    private java.lang.String wcOpenid;

    /**
     * ‘0’ 无效 '1' 有效
     */
    private java.lang.String status;

    /**
     * 口令失效日期
     */
    private java.lang.String passInvalidDate;

    /**
     * 数据授权类型 ‘1’ 按地区,'2' 按经销商,'0',可看全部数据
     */
    private java.lang.String dataAuthType;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 创建时间
     */
    private java.lang.String createTime;

    /**
     * 最后更新人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 最后更新时间
     */
    private java.lang.String modifyTime;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.lang.String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(java.lang.String loginName) {
        this.loginName = loginName;
    }

    public java.lang.String getLoginPassword() {
        return this.loginPassword;
    }

    public void setLoginPassword(java.lang.String loginPassword) {
        this.loginPassword = loginPassword;
    }

    public java.lang.String getUserName() {
        return this.userName;
    }

    public void setUserName(java.lang.String userName) {
        this.userName = userName;
    }

    public java.lang.String getOaFdno() {
        return this.oaFdno;
    }

    public void setOaFdno(java.lang.String oaFdno) {
        this.oaFdno = oaFdno;
    }

    public java.lang.String getComCode() {
        return this.comCode;
    }

    public void setComCode(java.lang.String comCode) {
        this.comCode = comCode;
    }

    public java.lang.String getOrganizationNo() {
        return this.organizationNo;
    }

    public void setOrganizationNo(java.lang.String organizationNo) {
        this.organizationNo = organizationNo;
    }

    public java.lang.String getRegistDate() {
        return this.registDate;
    }

    public void setRegistDate(java.lang.String registDate) {
        this.registDate = registDate;
    }

    public java.lang.String getRegistUser() {
        return this.registUser;
    }

    public void setRegistUser(java.lang.String registUser) {
        this.registUser = registUser;
    }

    public java.lang.String getSex() {
        return this.sex;
    }

    public void setSex(java.lang.String sex) {
        this.sex = sex;
    }

    public java.lang.String getMobile() {
        return this.mobile;
    }

    public void setMobile(java.lang.String mobile) {
        this.mobile = mobile;
    }

    public java.lang.String getEmail() {
        return this.email;
    }

    public void setEmail(java.lang.String email) {
        this.email = email;
    }

    public java.lang.String getWcOpenid() {
        return this.wcOpenid;
    }

    public void setWcOpenid(java.lang.String wcOpenid) {
        this.wcOpenid = wcOpenid;
    }

    public java.lang.String getStatus() {
        return this.status;
    }

    public void setStatus(java.lang.String status) {
        this.status = status;
    }

    public java.lang.String getPassInvalidDate() {
        return this.passInvalidDate;
    }

    public void setPassInvalidDate(java.lang.String passInvalidDate) {
        this.passInvalidDate = passInvalidDate;
    }

    public java.lang.String getDataAuthType() {
        return this.dataAuthType;
    }

    public void setDataAuthType(java.lang.String dataAuthType) {
        this.dataAuthType = dataAuthType;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public java.lang.String getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.lang.String createTime) {
        this.createTime = createTime;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public java.lang.String getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.lang.String modifyTime) {
        this.modifyTime = modifyTime;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}