package com.yqjr.fin.mkmm.sales.entity;

import com.alibaba.fastjson.annotation.JSONField;
import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;

public class ActiveDealerMatch extends BaseEntity<ActiveDealerMatch> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/activeDealerMatch/list
     *表单维护路径：/activeDealerMatch/form
     *
     */

    /**
     * ID
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 经销商代码
     */
    @Length(min = 0, max = 100)
    private String distributorCode;

    /**
     * 经销商名称
     */
    @Length(min = 0, max = 100)
    private String distributorName;

    /**
     * 经销商活动上限数量
     */
    @Digits(fraction =22,integer=0)
    private Long distributorCount;

    /**
     * 备注
     */
    @Length(min = 0, max = 500)
    private String remark;

    /**
     * 创建时间
     */
    @JSONField(format="yyyy-MM-dd HH-mm-ss")
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    @JSONField(format="yyyy-MM-dd HH-mm-ss")
    private java.util.Date modifyTime;

    /**
     * 生效时间
     */
    @JSONField(format="yyyy-MM-dd HH-mm-ss")
    private java.util.Date startTime;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 有效标识（如表记录不删除，以此区分,0无效，1有效）
     */
    @Length(min = 0, max = 10)
    private String flag;

    /**
     * 业务代码
     */
    @Length(min = 0, max = 20)
    private String businessCode;

    /**
     * 业务名称
     */
    @Length(min = 0, max = 64)
    private String businessName;

    /**
     * 经销商活动实际数量
     */
    @Digits(fraction =22,integer=0)
    private Long realDistributorCount;

    /**
     * 所属公司编码
     */
    @Length(min = 0, max = 20)
    private java.lang.String company;


    public Long getRealDistributorCount() {
        return realDistributorCount;
    }

    public void setRealDistributorCount(Long realDistributorCount) {
        this.realDistributorCount = realDistributorCount;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDistributorCode() {
        return this.distributorCode;
    }

    public void setDistributorCode(String distributorCode) {
        this.distributorCode = distributorCode;
    }

    public String getDistributorName() {
        return this.distributorName;
    }

    public void setDistributorName(String distributorName) {
        this.distributorName = distributorName;
    }

    public Long getDistributorCount() {
        return this.distributorCount;
    }

    public void setDistributorCount(Long distributorCount) {
        this.distributorCount = distributorCount;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public java.util.Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getBusinessCode() {
        return this.businessCode;
    }

    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    public String getBusinessName() {
        return this.businessName;
    }

    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    public java.lang.String getCompany() {
        return this.company;
    }

    public void setCompany(java.lang.String company) {
        this.company = company;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
