package com.yqjr.fin.mkmm.sales.entity;

import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.Digits;
import java.math.BigDecimal;
import java.util.Date;

public class CommodityOut extends BaseEntity<CommodityOut> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/commodityOut/list
     *表单维护路径：/commodityOut/form
     *
     */

    /**
     * 序号
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 物料名称
     */
    @Length(min = 0, max = 100)
    private String commodityName;

    /**
     * 物料编码
     */
    @Length(min = 0, max = 20)
    private String commodityCode;

    /**
     * 物料分类名称
     */
    @Length(min = 0, max = 100)
    private String commodityTypeName;

    /**
     * 物料分类编码
     */
    @Length(min = 0, max = 20)
    private String commodityTypeCode;

    /**
     * 项目名称
     */
    @Length(min = 0, max = 100)
    private String projectName;

    /**
     * 项目编码
     */
    @Length(min = 0, max = 20)
    private String projectCode;

    /**
     * 投放经销商编码
     */
    @Length(min = 0, max = 20)
    private String dealerCode;

    /**
     * 投放经销商名称
     */
    @Length(min = 0, max = 100)
    private String dealerName;

    /**
     * 区域编码
     */
    @Length(min = 0, max = 20)
    private String areaCode;

    /**
     * 区域名称
     */
    @Length(min = 0, max = 100)
    private String areaName;

    /**
     * 投放数量
     */
    @Digits(fraction =22,integer=0)
    private Long putNumber;

    /**
     * 投放单价
     */
    @Digits(fraction =14,integer=2)
    private BigDecimal putUnivalent;

    /**
     * 总金额
     */
    @Digits(fraction =14,integer=2)
    private BigDecimal amount;

    /**
     * 出库人 当前操作人
     */
    @Length(min = 0, max = 20)
    private String putName;

    /**
     * 校核人区域负责人审核
     */
    @Length(min = 0, max = 20)
    private String checker;

    /**
     * 出库时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date outTime;

    /**
     * 领用状态1：已领用，0：未领用
     */
    @Length(min = 0, max = 2)
    private String receiveStatus;

    /**
     * 领用人
     */
    @Length(min = 0, max = 20)
    private String receiver;

    /**
     * 领用时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date receiveTime;

    /**
     * 经销商意见反馈
     */
    @Length(min = 0, max = 530)
    private String opinion;

    /**
     * 物料状态
     */
    @Length(min = 0, max = 2)
    private String commodityStatus;

    /**
     * 公司1 ：汽车金融 ，2：租赁公司
     */
    @Length(min = 0, max = 2)
    private String company;

    /**
     * 创建时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private java.util.Date modifyTime;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCommodityName() {
        return this.commodityName;
    }

    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName;
    }

    public String getCommodityCode() {
        return this.commodityCode;
    }

    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode;
    }

    public String getCommodityTypeName() {
        return this.commodityTypeName;
    }

    public void setCommodityTypeName(String commodityTypeName) {
        this.commodityTypeName = commodityTypeName;
    }

    public String getCommodityTypeCode() {
        return this.commodityTypeCode;
    }

    public void setCommodityTypeCode(String commodityTypeCode) {
        this.commodityTypeCode = commodityTypeCode;
    }

    public String getProjectName() {
        return this.projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getProjectCode() {
        return this.projectCode;
    }

    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    public String getDealerCode() {
        return this.dealerCode;
    }

    public void setDealerCode(String dealerCode) {
        this.dealerCode = dealerCode;
    }

    public String getDealerName() {
        return this.dealerName;
    }

    public void setDealerName(String dealerName) {
        this.dealerName = dealerName;
    }

    public String getAreaCode() {
        return this.areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getAreaName() {
        return this.areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public Long getPutNumber() {
        return this.putNumber;
    }

    public void setPutNumber(Long putNumber) {
        this.putNumber = putNumber;
    }

    public BigDecimal getPutUnivalent() {
        return putUnivalent;
    }

    public void setPutUnivalent(BigDecimal putUnivalent) {
        this.putUnivalent = putUnivalent;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getPutName() {
        return this.putName;
    }

    public void setPutName(String putName) {
        this.putName = putName;
    }

    public String getChecker() {
        return this.checker;
    }

    public void setChecker(String checker) {
        this.checker = checker;
    }

    public Date getOutTime() {
        return this.outTime;
    }

    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    public String getReceiveStatus() {
        return this.receiveStatus;
    }

    public void setReceiveStatus(String receiveStatus) {
        this.receiveStatus = receiveStatus;
    }

    public String getReceiver() {
        return this.receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public Date getReceiveTime() {
        return receiveTime;
    }

    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    public String getOpinion() {
        return this.opinion;
    }

    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }

    public String getCommodityStatus() {
        return this.commodityStatus;
    }

    public void setCommodityStatus(String commodityStatus) {
        this.commodityStatus = commodityStatus;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
