package com.yqjr.fin.mkmm.sales.entity;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;
import java.math.BigDecimal;
import java.util.Date;

public class DealerSale extends BaseEntity<DealerSale> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/dealerSale/list
     *表单维护路径：/dealerSale/form
     *
     */

    /**
     * 序列
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 大区代码
     */
    @Length(min = 0, max = 32)
    private String superorganizationno;

    /**
     * 二区代码
     */
    @Length(min = 0, max = 20)
    private String vsuperorganizationno;

    /**
     * 经销商代码
     */
    @Length(min = 0, max = 32)
    private String vorganizationno;

    /**
     * 销售顾问代码
     */
    @Digits(fraction =22,integer=0)
    private Long ndealerworkerid;

    /**
     * 省份
     */
    @Length(min = 0, max = 16)
    private String provinceid;

    /**
     * 城市
     */
    @Length(min = 0, max = 100)
    private String cityid;

    /**
     * 合同号
     */
    @Length(min = 0, max = 50)
    private String vbargainno;

    /**
     * 借据号
     */
    @Length(min = 0, max = 50)
    private String vbargain;

    /**
     * 客户名称
     */
    @Length(min = 0, max = 200)
    private String name;

    /**
     * 证件号
     */
    @Length(min = 0, max = 50)
    private String identityno;

    /**
     * 大品牌
     */
    @Digits(fraction =22,integer=0)
    private Long ncarbrandid;

    /**
     * 子品牌
     */
    @Digits(fraction =22,integer=0)
    private Long ncarsubbrandid;

    /**
     * 车型
     */
    @Digits(fraction =22,integer=0)
    private Long ncarbrandtype;

    /**
     * 净车价
     */
    @Digits(fraction =2,integer=16)
    private BigDecimal ncarprice;

    /**
     * 车籍
     */
    @Length(min = 0, max = 200)
    private String vmortgagername;

    /**
     * 车贷金融产品id  营销活动
     */
    @Digits(fraction =22,integer=0)
    private Long nactivitiesid;

    /**
     * 附加费金融产品id
     */
    @Digits(fraction =22,integer=0)
    private Long necactivitiesid;

    /**
     * 业务类型Code
     */
    @Digits(fraction =22,integer=0)
    private Long nbiztype;

    /**
     * 信贷产品Code  
     */
    @Digits(fraction =22,integer=0)
    private Long ngetinteresttype;

    /**
     * 服务产品Code  金融产品
     */
    @Digits(fraction =22,integer=0)
    private Long ndlrbiztype;

    /**
     * 公司
     */
    @Length(min = 0, max = 20)
    private java.lang.String company;

    public java.lang.String getCompany() {
        return this.company;
    }

    public void setCompany(java.lang.String company) {
        this.company = company;
    }

    /**
     * 贷款金额
     */
    @Digits(fraction =16,integer=2)
    private Long nloanmoney;

    /**
     * 贷款期限
     */
    @Digits(fraction =22,integer=0)
    private Long ntimelimit;

    /**
     * 申请日期
     */
    private java.util.Date dapplydate;

    /**
     * 放款日期
     */
    private java.util.Date dfactstartdate;

    /**
     * 附加贷金额
     */
    @Digits(fraction =16,integer=2)
    private Long necloanmoney;

    /**
     * 首付比例
     */
    @Digits(fraction =22,integer=0)
    private Long firstpay;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSuperorganizationno() {
        return this.superorganizationno;
    }

    public void setSuperorganizationno(String superorganizationno) {
        this.superorganizationno = superorganizationno;
    }

    public String getVsuperorganizationno() {
        return this.vsuperorganizationno;
    }

    public void setVsuperorganizationno(String vsuperorganizationno) {
        this.vsuperorganizationno = vsuperorganizationno;
    }

    public String getVorganizationno() {
        return this.vorganizationno;
    }

    public void setVorganizationno(String vorganizationno) {
        this.vorganizationno = vorganizationno;
    }

    public Long getNdealerworkerid() {
        return this.ndealerworkerid;
    }

    public void setNdealerworkerid(Long ndealerworkerid) {
        this.ndealerworkerid = ndealerworkerid;
    }

    public String getProvinceid() {
        return this.provinceid;
    }

    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    public String getCityid() {
        return this.cityid;
    }

    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    public String getVbargainno() {
        return this.vbargainno;
    }

    public void setVbargainno(String vbargainno) {
        this.vbargainno = vbargainno;
    }

    public String getVbargain() {
        return this.vbargain;
    }

    public void setVbargain(String vbargain) {
        this.vbargain = vbargain;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIdentityno() {
        return this.identityno;
    }

    public void setIdentityno(String identityno) {
        this.identityno = identityno;
    }

    public Long getNcarbrandid() {
        return this.ncarbrandid;
    }

    public void setNcarbrandid(Long ncarbrandid) {
        this.ncarbrandid = ncarbrandid;
    }

    public Long getNcarsubbrandid() {
        return this.ncarsubbrandid;
    }

    public void setNcarsubbrandid(Long ncarsubbrandid) {
        this.ncarsubbrandid = ncarsubbrandid;
    }

    public Long getNcarbrandtype() {
        return this.ncarbrandtype;
    }

    public void setNcarbrandtype(Long ncarbrandtype) {
        this.ncarbrandtype = ncarbrandtype;
    }

    public BigDecimal getNcarprice() {
        return ncarprice;
    }

    public void setNcarprice(BigDecimal ncarprice) {
        this.ncarprice = ncarprice;
    }

    public String getVmortgagername() {
        return this.vmortgagername;
    }

    public void setVmortgagername(String vmortgagername) {
        this.vmortgagername = vmortgagername;
    }

    public Long getNactivitiesid() {
        return this.nactivitiesid;
    }

    public void setNactivitiesid(Long nactivitiesid) {
        this.nactivitiesid = nactivitiesid;
    }

    public Long getNecactivitiesid() {
        return this.necactivitiesid;
    }

    public void setNecactivitiesid(Long necactivitiesid) {
        this.necactivitiesid = necactivitiesid;
    }

    public Long getNbiztype() {
        return this.nbiztype;
    }

    public void setNbiztype(Long nbiztype) {
        this.nbiztype = nbiztype;
    }

    public Long getNgetinteresttype() {
        return this.ngetinteresttype;
    }

    public void setNgetinteresttype(Long ngetinteresttype) {
        this.ngetinteresttype = ngetinteresttype;
    }

    public Long getNdlrbiztype() {
        return this.ndlrbiztype;
    }

    public void setNdlrbiztype(Long ndlrbiztype) {
        this.ndlrbiztype = ndlrbiztype;
    }

    public Long getNloanmoney() {
        return this.nloanmoney;
    }

    public void setNloanmoney(Long nloanmoney) {
        this.nloanmoney = nloanmoney;
    }

    public Long getNtimelimit() {
        return this.ntimelimit;
    }

    public void setNtimelimit(Long ntimelimit) {
        this.ntimelimit = ntimelimit;
    }

    public Date getDapplydate() {
        return dapplydate;
    }

    public void setDapplydate(Date dapplydate) {
        this.dapplydate = dapplydate;
    }

    public Date getDfactstartdate() {
        return dfactstartdate;
    }

    public void setDfactstartdate(Date dfactstartdate) {
        this.dfactstartdate = dfactstartdate;
    }

    public Long getNecloanmoney() {
        return this.necloanmoney;
    }

    public void setNecloanmoney(Long necloanmoney) {
        this.necloanmoney = necloanmoney;
    }

    public Long getFirstpay() {
        return this.firstpay;
    }

    public void setFirstpay(Long firstpay) {
        this.firstpay = firstpay;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
