package com.yqjr.fin.mkmm.sales.entity;

import com.alibaba.fastjson.annotation.JSONField;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.Digits;

public class PersonTeamReview extends BaseEntity<PersonTeamReview> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/personTeamReview/list
     *表单维护路径：/personTeamReview/form
     *
     */

    /**
     * 序列
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 人员代码
     */
    @Length(min = 0, max = 32)
    private java.lang.String personCode;


    /**
     * 团队代码
     */
    @Length(min = 0, max = 32)
    private java.lang.String teamCode;

    /**
     * 人员性质（0团队负责人，1销售经理）
     */
    @Length(min = 0, max = 20)
    private java.lang.String personNature;

    /**
     * 人员级别
     */
    @Length(min = 0, max = 6)
    private java.lang.String personLevel;

    /**
     * 人员状态(0 无效,1 有效，2 注销)
     */
    @Length(min = 0, max = 6)
    private java.lang.String personStatus;

    /**
     * 考核开始时间
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date personCheckStart;

    /**
     * 上岗时间
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date personUptime;

    /**
     * 转正时间
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date personCorrectime;

    /**
     * 试用期开始时间
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date personTryStartime;

    /**
     * 试用期结束时间
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date personTryEndtime;

    /**
     * 加入我司时间
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date personJointime;

    /**
     * 备注
     */
    @Length(min = 0, max = 256)
    private java.lang.String remark;

    /**
     * 审核状态（00驳回,01提交审核,02待审核,03审核中,04审核通过）
     */
    @Length(min = 0, max = 4)
    private java.lang.String reviewStatus;

    /**
     * 生效时间
     */

    @JSONField(format="yyyy-MM-dd")
    private java.util.Date startTime;

    /**
     * 创建时间
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private java.util.Date modifyTime;

    /**
     * 创建人
     */
    @Digits(fraction =32,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =32,integer=0)
    private Long modifier;

    /**
     * 有效标识（如表记录不删除，以此区分,0无效，1有效）
     */
    @Length(min = 0, max = 4)
    private java.lang.String flag;

    /**
     * 审核类型（01人员新增，02人员修改）
     */
    @Length(min = 0, max = 4)
    private java.lang.String reviewType;

    /**
     * 工作流id
     */
    @Digits(fraction =22,integer=0)
    private Long flowId;

    /**
     * 区域代码
     */
    @Length(min = 0, max = 32)
    private java.lang.String areaCode;

    /**
     * 人员审核表id
     */
    @Digits(fraction =22,integer=0)
    private Long personMainReviewId;

    /**
     * 区域名称
     */
    @Length(min = 0, max = 128)
    private java.lang.String areaName;

    /**
     * 团队名称
     */
    @Length(min = 0, max = 128)
    private java.lang.String teamName;

    /*****
     * 登录用户名
     * */
    @Length(min = 0, max = 50)
    private java.lang.String  searchPerson;

    /****
     *
     * 提交人名称
     * */
    private String createName;

    /**
     * 公司
     */
    @Length(min = 0, max = 20)
    private java.lang.String company;

    public java.lang.String getCompany() {
        return this.company;
    }

    public void setCompany(java.lang.String company) {
        this.company = company;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.lang.String getPersonCode() {
        return this.personCode;
    }

    public void setPersonCode(java.lang.String personCode) {
        this.personCode = personCode;
    }

    public java.lang.String getTeamCode() {
        return this.teamCode;
    }

    public void setTeamCode(java.lang.String teamCode) {
        this.teamCode = teamCode;
    }

    public java.lang.String getPersonNature() {
        return this.personNature;
    }

    public void setPersonNature(java.lang.String personNature) {
        this.personNature = personNature;
    }

    public java.lang.String getPersonLevel() {
        return this.personLevel;
    }

    public void setPersonLevel(java.lang.String personLevel) {
        this.personLevel = personLevel;
    }

    public java.lang.String getPersonStatus() {
        return this.personStatus;
    }

    public void setPersonStatus(java.lang.String personStatus) {
        this.personStatus = personStatus;
    }

    public java.util.Date getPersonCheckStart() {
        return this.personCheckStart;
    }

    public void setPersonCheckStart(java.util.Date personCheckStart) {
        this.personCheckStart = personCheckStart;
    }

    public java.util.Date getPersonUptime() {
        return this.personUptime;
    }

    public void setPersonUptime(java.util.Date personUptime) {
        this.personUptime = personUptime;
    }

    public java.util.Date getPersonCorrectime() {
        return this.personCorrectime;
    }

    public void setPersonCorrectime(java.util.Date personCorrectime) {
        this.personCorrectime = personCorrectime;
    }

    public java.util.Date getPersonTryStartime() {
        return this.personTryStartime;
    }

    public void setPersonTryStartime(java.util.Date personTryStartime) {
        this.personTryStartime = personTryStartime;
    }

    public java.util.Date getPersonTryEndtime() {
        return this.personTryEndtime;
    }

    public void setPersonTryEndtime(java.util.Date personTryEndtime) {
        this.personTryEndtime = personTryEndtime;
    }

    public java.util.Date getPersonJointime() {
        return this.personJointime;
    }

    public void setPersonJointime(java.util.Date personJointime) {
        this.personJointime = personJointime;
    }

    public java.lang.String getRemark() {
        return this.remark;
    }

    public void setRemark(java.lang.String remark) {
        this.remark = remark;
    }

    public java.lang.String getReviewStatus() {
        return this.reviewStatus;
    }

    public void setReviewStatus(java.lang.String reviewStatus) {
        this.reviewStatus = reviewStatus;
    }

    public java.util.Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public java.lang.String getFlag() {
        return this.flag;
    }

    public void setFlag(java.lang.String flag) {
        this.flag = flag;
    }

    public java.lang.String getReviewType() {
        return this.reviewType;
    }

    public void setReviewType(java.lang.String reviewType) {
        this.reviewType = reviewType;
    }

    public Long getFlowId() {
        return this.flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public java.lang.String getAreaCode() {
        return this.areaCode;
    }

    public void setAreaCode(java.lang.String areaCode) {
        this.areaCode = areaCode;
    }

    public Long getPersonMainReviewId() {
        return this.personMainReviewId;
    }

    public void setPersonMainReviewId(Long personMainReviewId) {
        this.personMainReviewId = personMainReviewId;
    }

    public java.lang.String getAreaName() {
        return this.areaName;
    }

    public void setAreaName(java.lang.String areaName) {
        this.areaName = areaName;
    }

    public java.lang.String getTeamName() {
        return this.teamName;
    }

    public void setTeamName(java.lang.String teamName) {
        this.teamName = teamName;
    }

    public String getSearchPerson() {
        return searchPerson;
    }

    public void setSearchPerson(String searchPerson) {
        this.searchPerson = searchPerson;
    }

    public String getCreateName() {
        return createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName;
    }


//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
