package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/personPlan")
public class PersonPlanController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/personplan/personPlanList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/personplan/personPlanView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/personplan/personPlanForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/personplan/personPlanModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/personplan/personPlanModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/personplan/personPlanListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}