
package com.yqjr.fin.mkmm.sales.condition;

import com.alibaba.fastjson.annotation.JSONField;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Digits;

import com.yqjr.scfw.common.condition.BaseCondition;

import com.yqjr.fin.mkmm.sales.entity.PersonMainReview;
import org.springframework.format.annotation.DateTimeFormat;

public class PersonMainReviewCondition extends BaseCondition<PersonMainReview, Long> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/personMainReview/list
     *表单维护路径：/personMainReview/form
     *
     */

    /**
     * 序列
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 人员代码
     */
    @Length(min = 0, max = 16)
    private java.lang.String personCode;

    /**
     * 人员姓名
     */
    @Length(min = 0, max = 32)
    private java.lang.String personName;

    /**
     * 身份证号
     */
    @Length(min = 0, max = 18)
    private java.lang.String personIdcard;

    /**
     * 备注
     */
    @Length(min = 0, max = 1000)
    private java.lang.String remark;

    /**
     * 年龄
     */
    @Length(min = 0, max = 4)
    private java.lang.String personAge;

    /**
     * 民族
     */
    @Length(min = 0, max = 10)
    private java.lang.String personEthnic;

    /**
     * 婚姻状况
     */
    @Length(min = 0, max = 12)
    private java.lang.String personMarr;

    /**
     * 毕业学校
     */
    @Length(min = 0, max = 32)
    private java.lang.String personSchool;

    /**
     * 专业
     */
    @Length(min = 0, max = 32)
    private java.lang.String personSubject;

    /**
     * 最高学历
     */
    @Length(min = 0, max = 32)
    private java.lang.String personEdu;

    /**
     * 学位
     */
    @Length(min = 0, max = 32)
    private java.lang.String personEdulevel;

    /**
     * 工龄
     */
    @Length(min = 0, max = 10)
    private java.lang.String personWorktime;

    /**
     * 参加工作时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private java.lang.String personFirstworktime;

    /**
     * 家庭住址
     */
    @Length(min = 0, max = 1000)
    private java.lang.String personAddress;

    /**
     * 家庭电话
     */
    @Length(min = 0, max = 20)
    private java.lang.String personHomephone;

    /**
     * 工作电话
     */
    @Length(min = 0, max = 12)
    private java.lang.String personWorkphone;

    /**
     * 移动电话
     */
    @Length(min = 0, max = 11)
    private java.lang.String personPhone;

    /**
     * e-mail
     */
    @Length(min = 0, max = 32)
    private java.lang.String personEmail;

    /**
     * 生效时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private java.util.Date startTime;

    /**
     * 创建时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private java.util.Date modifyTime;

    /**
     * 创建人
     */
    @Digits(fraction =32,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =32,integer=0)
    private Long modifier;

    /**
     * 出生日期
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private java.lang.String personBirth;

    /**
     * 登陆姓名
     */
    @Length(min = 0, max = 50)
    private java.lang.String loginName;

    /**
     * 所属公司
     */
    @Length(min = 0, max = 20)
    private java.lang.String company;

    /**
     * 人员团队审核表id
     */
    @Digits(fraction =22,integer=0)
    private Long personTeamReviewId;

    public Long getPersonTeamReviewId() {
        return personTeamReviewId;
    }

    public void setPersonTeamReviewId(Long personTeamReviewId) {
        this.personTeamReviewId = personTeamReviewId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.lang.String getPersonCode() {
        return this.personCode;
    }

    public void setPersonCode(java.lang.String personCode) {
        this.personCode = personCode;
    }

    public java.lang.String getPersonName() {
        return this.personName;
    }

    public void setPersonName(java.lang.String personName) {
        this.personName = personName;
    }

    public java.lang.String getPersonIdcard() {
        return this.personIdcard;
    }

    public void setPersonIdcard(java.lang.String personIdcard) {
        this.personIdcard = personIdcard;
    }

    public java.lang.String getRemark() {
        return this.remark;
    }

    public void setRemark(java.lang.String remark) {
        this.remark = remark;
    }

    public java.lang.String getPersonAge() {
        return this.personAge;
    }

    public void setPersonAge(java.lang.String personAge) {
        this.personAge = personAge;
    }

    public java.lang.String getPersonEthnic() {
        return this.personEthnic;
    }

    public void setPersonEthnic(java.lang.String personEthnic) {
        this.personEthnic = personEthnic;
    }

    public java.lang.String getPersonMarr() {
        return this.personMarr;
    }

    public void setPersonMarr(java.lang.String personMarr) {
        this.personMarr = personMarr;
    }

    public java.lang.String getPersonSchool() {
        return this.personSchool;
    }

    public void setPersonSchool(java.lang.String personSchool) {
        this.personSchool = personSchool;
    }

    public java.lang.String getPersonSubject() {
        return this.personSubject;
    }

    public void setPersonSubject(java.lang.String personSubject) {
        this.personSubject = personSubject;
    }

    public java.lang.String getPersonEdu() {
        return this.personEdu;
    }

    public void setPersonEdu(java.lang.String personEdu) {
        this.personEdu = personEdu;
    }

    public java.lang.String getPersonEdulevel() {
        return this.personEdulevel;
    }

    public void setPersonEdulevel(java.lang.String personEdulevel) {
        this.personEdulevel = personEdulevel;
    }

    public java.lang.String getPersonWorktime() {
        return this.personWorktime;
    }

    public void setPersonWorktime(java.lang.String personWorktime) {
        this.personWorktime = personWorktime;
    }

    public java.lang.String getPersonFirstworktime() {
        return this.personFirstworktime;
    }

    public void setPersonFirstworktime(java.lang.String personFirstworktime) {
        this.personFirstworktime = personFirstworktime;
    }

    public java.lang.String getPersonAddress() {
        return this.personAddress;
    }

    public void setPersonAddress(java.lang.String personAddress) {
        this.personAddress = personAddress;
    }

    public java.lang.String getPersonHomephone() {
        return this.personHomephone;
    }

    public void setPersonHomephone(java.lang.String personHomephone) {
        this.personHomephone = personHomephone;
    }

    public java.lang.String getPersonWorkphone() {
        return this.personWorkphone;
    }

    public void setPersonWorkphone(java.lang.String personWorkphone) {
        this.personWorkphone = personWorkphone;
    }

    public java.lang.String getPersonPhone() {
        return this.personPhone;
    }

    public void setPersonPhone(java.lang.String personPhone) {
        this.personPhone = personPhone;
    }

    public java.lang.String getPersonEmail() {
        return this.personEmail;
    }

    public void setPersonEmail(java.lang.String personEmail) {
        this.personEmail = personEmail;
    }

    public java.util.Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public java.lang.String getPersonBirth() {
        return this.personBirth;
    }

    public void setPersonBirth(java.lang.String personBirth) {
        this.personBirth = personBirth;
    }

    public java.lang.String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(java.lang.String loginName) {
        this.loginName = loginName;
    }
    public java.lang.String getCompany() {
        return this.company;
    }

    public void setCompany(java.lang.String company) {
        this.company = company;
    }

    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}