package com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.fyafdynamicbillservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-06-07T15:07:01.027+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://service.fyafdynamicbillservice.server.charge.yqjr.webservice.cc.epoch.com/", name = "FYAFDynamicBillService")
@XmlSeeAlso({ObjectFactory.class})
public interface FYAFDynamicBillService {

    @WebMethod
    @RequestWrapper(localName = "createBill4FYAFDynamicBillService", targetNamespace = "http://service.fyafdynamicbillservice.server.charge.yqjr.webservice.cc.epoch.com/", className = "com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.fyafdynamicbillservice.CreateBill4FYAFDynamicBillService")
    @ResponseWrapper(localName = "createBill4FYAFDynamicBillServiceResponse", targetNamespace = "http://service.fyafdynamicbillservice.server.charge.yqjr.webservice.cc.epoch.com/", className = "com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.fyafdynamicbillservice.CreateBill4FYAFDynamicBillServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.fyafdynamicbillservice.Message createBill4FYAFDynamicBillService(
            @WebParam(name = "mainVO", targetNamespace = "")
            com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.fyafdynamicbillservice.FyafDynamicBillMainVO mainVO,
            @WebParam(name = "detailVOList", targetNamespace = "")
            java.util.List<com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.fyafdynamicbillservice.FyafDynamicBillDetailVO> detailVOList
    ) throws Exception_Exception;
}
