package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.EventTeamCondition;
import com.yqjr.fin.mkmm.sales.entity.FeeMainReview;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.EventTeam;
import com.yqjr.scfw.common.pagination.model.PageBounds;

import java.util.List;

public interface EventTeamMapper extends Mapper<EventTeam, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    //综合查询，查团队重大事件
    List<EventTeam> queryTeamEventByCode(String teamCode,String company );

    //模糊查询重大事件列表
    List<EventTeam> queryEventTeam(EventTeamCondition eventTeamCondition, PageBounds... pageBounds);

    //添加重大事项增加权限
    List<EventTeam> queryTeamMainByName(String teamName, String company);



}

