package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.entity.PersonTeamReview;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonMainVo;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.PersonMainHis;

import java.util.List;

public interface PersonMainHisMapper extends Mapper<PersonMainHis, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    List<PersonMainHis>  selectPersonMainHisByCode(String personCode);


    PersonMainVo selectPersonMainVoById(Long id);


	//endregion
	
}
