package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.PersonTeamReviewCondition;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.PersonTeamReview;

import java.util.List;

public interface PersonTeamReviewMapper extends Mapper<PersonTeamReview, Long> {

    //region generated by CodeRobot

    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    String queryMax(String teamCode);

    Integer updateByPersonCodeAndId(PersonTeamReview personTeamReview);

    List<PersonTeamReview> selectByPersonCode(String personCode);

    Integer updateByPersonCode(PersonTeamReview personTeamReview);

    List<PersonTeamReview> selectPersonTeamReviewByPersonCode(String personCode);


    //endregion

    PersonTeamReview selectOneT(PersonTeamReviewCondition condition);

}
