package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.PlanTrackCondition;
import com.yqjr.fin.mkmm.sales.entity.AreaMain;
import com.yqjr.fin.mkmm.sales.entity.PersonSale;
import com.yqjr.fin.mkmm.sales.entity.PersonTeam;
import com.yqjr.fin.mkmm.sales.entity.PlanTrack;
import com.yqjr.fin.mkmm.sales.model.PlanTrackVo;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.scfw.common.pagination.model.PageBounds;

import java.util.List;

public interface PlanTrackMapper extends Mapper<PlanTrack, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    //先查有多少区域
    List<PersonTeam> selectAllArea();
    //每个区域多少人
    List<PersonTeam> selectPersonCodeByAreaCode(String areaCode);
    //查人姓名
    String selectPersonNameByCode(String personCode);
    //查询是否存在记录
    List<PlanTrack> selectTrackExist(PlanTrack planTrack);
    //更新MKMM_PLAN_TRACK
    void updatePlanTrack(PlanTrack planTrack);
    //更新当前年之前月份的年序时进度和差值
    void updatePlanTrackRate(PlanTrack planTrack);

    //计算计划跟踪
    List<PlanTrackVo> sumPlanTrack(PlanTrackCondition planTrackCondition, PageBounds... pageBounds);

    //计算计划跟踪
    List<PlanTrackVo> sumPlanTrack(PlanTrackCondition planTrackCondition);

}
