package com.yqjr.fin.scfw.isomer.mapper;

import com.yqjr.fin.scfw.isomer.entity.IsomerDynamicBill;
import com.yqjr.scfw.common.mapper.Mapper;


public interface IsomerDynamicBillMapper extends Mapper<IsomerDynamicBill, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
	
}
