package com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.fyzldynamicbillservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-06-07T15:05:39.059+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "FYZLDynamicBillServiceImplService", 
                  wsdlLocation = "file:/C:/Users/THINK/Desktop/一汽销管平台/活动动支相关//FYZLDynamicBillService.wsdl",
                  targetNamespace = "http://service.fyzldynamicbillservice.server.charge.yqjr.webservice.cc.epoch.com/") 
public class FYZLDynamicBillServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.fyzldynamicbillservice.server.charge.yqjr.webservice.cc.epoch.com/", "FYZLDynamicBillServiceImplService");
    public final static QName FYZLDynamicBillServiceImplPort = new QName("http://service.fyzldynamicbillservice.server.charge.yqjr.webservice.cc.epoch.com/", "FYZLDynamicBillServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/THINK/Desktop/一汽销管平台/活动动支相关//FYZLDynamicBillService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FYZLDynamicBillServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/THINK/Desktop/一汽销管平台/活动动支相关//FYZLDynamicBillService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FYZLDynamicBillServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FYZLDynamicBillServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FYZLDynamicBillServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FYZLDynamicBillServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FYZLDynamicBillServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FYZLDynamicBillServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns FYZLDynamicBillService
     */
    @WebEndpoint(name = "FYZLDynamicBillServiceImplPort")
    public FYZLDynamicBillService getFYZLDynamicBillServiceImplPort() {
        return super.getPort(FYZLDynamicBillServiceImplPort, FYZLDynamicBillService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FYZLDynamicBillService
     */
    @WebEndpoint(name = "FYZLDynamicBillServiceImplPort")
    public FYZLDynamicBillService getFYZLDynamicBillServiceImplPort(WebServiceFeature... features) {
        return super.getPort(FYZLDynamicBillServiceImplPort, FYZLDynamicBillService.class, features);
    }

}
