package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.EventPersonCondition;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.EventPerson;
import com.yqjr.scfw.common.pagination.model.PageBounds;

import java.util.List;

public interface EventPersonMapper extends Mapper<EventPerson, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
    public List<EventPerson> selectT(EventPersonCondition eventPersonCondition);

    //模糊查询重大事件列表
    List<EventPerson> queryEventPerson(EventPersonCondition eventPersonCondition, PageBounds... pageBounds);
	
}
