package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.PersonMainCondition;

import com.yqjr.fin.mkmm.sales.condition.PersonWorkCondition;
import com.yqjr.fin.mkmm.sales.entity.PersonMain;
import com.yqjr.fin.mkmm.sales.rest.vo.PersonMainAndTeam;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonMainVo;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonTeamVo;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.scfw.common.pagination.model.PageBounds;

import java.util.List;

public interface PersonMainMapper extends Mapper<PersonMain, Long> {

    //region generated by CodeRobot

    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    int patchByPersonCode(PersonMain personMain);

    /**
     * 模糊查询
     *
     * @param personMainAndTeam
     * @return
     */
    List<PersonMain> queryPersonMainList(PersonMainAndTeam personMainAndTeam);


    public List<PersonMainVo> selectPersonMainList(PersonWorkCondition condition);

    public List<PersonMainVo> selectPersonMainTable(PersonWorkCondition condition, PageBounds... pageBounds);//查询销售人员列表

    public PersonMainVo selectPersonMainById(Long id);//通过id查询审核通过人员信息


    public PersonMainVo selectPersonMainByflowId(Long flowId);//通过flowId查询审核通过人员信息

    //综合查询通过人员代码模糊查询
    public List<PersonTeamVo> queryPersonBypersonCode(String personCode);
    //endregion
    List<PersonMain> selectAllNoStatus();
    public List<PersonMain> selectByCode(String personCode);

    List<PersonMain> selectPersonMainByCode(PersonMain personMain);
}
