package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.entity.PersonSale;
import com.yqjr.fin.mkmm.sales.entity.PersonTeam;
import com.yqjr.fin.mkmm.sales.entity.TeamSale;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonMainVo;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonVo;
import com.yqjr.scfw.common.mapper.Mapper;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.List;

@Service
public interface PersonSaleMapper extends Mapper<PersonSale, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    //查人的月实际完成合计
    Long selectActualByMonth(PersonSale personSale);
    //查询人姓名
    String qryPersonByCode(PersonVo pv);

    //先查有多少人
    List<String> selectAllPersonCode();
    //计算每个人每天发生的数量
    Long getPersonSaleDaily(String personCode, Date date, String Brands);
    //查询每个人达成台数
    Long qryOldPersonSale(PersonSale personSale);
    //查询是否有记录
    List<PersonSale> selectPersonExist(PersonSale personSale);
    //更新mkmm_person_sale的实际销售
    void updatePersonSale(PersonSale personSale);
    //获取每个人的实际达成数量
    Long querySumPersonSale(String personCode,String brands,String year,String month);
    //根据团队编码查找人
    List<PersonTeam> queryPersonByTeamCode(PersonTeam personTeam);
    //查人
    List<PersonSale> queryPersonExitByCode( String personCode,String company);

}
