package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.entity.AreaMain;
import com.yqjr.scfw.common.mapper.Mapper;

import java.util.List;

public interface AreaMainMapper extends Mapper<AreaMain, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion


}
