package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.BasicBussiness;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface
BasicBussinessMapper extends Mapper<BasicBussiness, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    List<BasicBussiness> selectByDfactatartDate(String dfactstartDate);

    List<BasicBussiness> selectByPlanInfo(Map<String,Object> paramMap);
  
    Map<String,Object> selectPersonByDealer(Map<String,String> map);

    List<BasicBussiness> selectSaleViewByDate(Date date);
}
