package com.yqjr.fin.mkmm.sales.mapper;


import com.yqjr.fin.mkmm.sales.condition.TeamReviewCondition;
import com.yqjr.fin.mkmm.sales.condition.TeamWorkCondition;
import com.yqjr.fin.mkmm.sales.entity.TeamHis;
import com.yqjr.fin.mkmm.sales.model.TeamReviewWork;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonTeamVo;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.TeamReview;
import com.yqjr.scfw.common.pagination.model.PageBounds;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface TeamReviewMapper extends Mapper<TeamReview, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
    String queryMax(String areaCode);
    List<TeamReviewWork> queryWorkFlow(TeamWorkCondition teamWorkCondition, PageBounds... pageBounds);

    /**
     * 团队新增时团队名称唯一性校验
     * @param teamName
     * @return
     */
    Integer selectByCheckUniquen(@Param("teamName") String teamName,@Param("company") String company);

    //综合查询，查历史记录
    List<TeamHis> queryTeamHisByReviewId(@Param("reviewId") Long reviewId);

    //综合查询，查reviewde的数据
    List<TeamReview> queryTeamReviewByCode(@Param("teamCode")String teamCode,
                                           @Param("reviewStatus")String reviewStatus,
                                           @Param("company")String company);

    //活动审核进度
    List<TeamReview> selectProcessList(TeamReviewCondition condition, PageBounds of);
}

