package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.entity.PersonTeam;
import com.yqjr.fin.mkmm.sales.entity.TeamMain;
import com.yqjr.fin.mkmm.sales.entity.TeamSale;
import com.yqjr.scfw.common.mapper.Mapper;

import java.util.List;

public interface TeamSaleMapper extends Mapper<TeamSale, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    //求和
    Long selectActualByMonth(TeamSale teamSale);

    //根据团队编码查找人
    List<PersonTeam> queryPersonByTeamCode(PersonTeam personTeam);

    //查有团队
    List<String> selectAllTeam(String company);
    //获取每个团队每天每个品牌的发生的数量
    Long selectAllPersonSale(String teamCode, String year, String month, String brand, String company);
    //查询团队之前的实际销售
    Long queryOldTeamSale(TeamSale teamSale);
    //查询是否有符合条件的记录记录
    List<TeamSale> selectTeamExist(TeamSale teamSale);
    //更新mkmm_team_sale的实际销售
    void updateTeamSale(TeamSale teamSale);
    //查询团队名称
    String qryTeamByCode(String teamCode, String company);

    List<TeamSale> selectTeamByCode(TeamMain tm);
}
