package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.ActiveMainAllListCondition;
import com.yqjr.fin.mkmm.sales.condition.ActiveMainCondition;
import com.yqjr.fin.mkmm.sales.condition.ActiveMainListCondition;
import com.yqjr.fin.mkmm.sales.entity.ActiveMatchTask;
import com.yqjr.fin.mkmm.sales.rest.vo.ActiveMainVo;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.ActiveMain;
import com.yqjr.scfw.common.pagination.model.PageBounds;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface ActiveMainMapper extends Mapper<ActiveMain, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    /**
     * 根据code查活动主表
     * create by fanna 20180604
     * @param areaCode
     * @return
     */
    List<ActiveMain>  selectActiveMainByCode(String areaCode,String company);



    List<ActiveMain> selectByLoanEndTime(String loanEndTime);

    int insert(ActiveMatchTask activeMatchTask);

    List<Map<String,Object>> getActiveMatchData(Long activeMainId);

    List<ActiveMainVo> selectMainActives(ActiveMainListCondition condition,PageBounds of);

    List<ActiveMainVo> selectMainAllActives(ActiveMainAllListCondition condition, PageBounds of);

    void patchByActiveCode(ActiveMain activeMain);

    Long insertAndReturnId(ActiveMain activeMain);

    List<ActiveMain> queryActiveMains(ActiveMainCondition activeMainCondition);
}
