package com.yqjr.fin.risk.stat.mapper;

import com.yqjr.fin.risk.stat.condition.FctAltCustomCondition;
import com.yqjr.fin.risk.stat.entity.FctAltCustom;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.scfw.common.pagination.model.PageBounds;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface FctAltCustomMapper extends Mapper<FctAltCustom, Long> {


	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    public List<FctAltCustom> selectFctAltCustomFenYe (FctAltCustomCondition condition, PageBounds of);
    public List<FctAltCustom> chaXunFctAltCustomFenYe (FctAltCustomCondition condition, PageBounds of);
    public List<FctAltCustom> selectFctAltCustomByEventid(FctAltCustom fctAltCustom);
    public void updateHandlestateByEventid(FctAltCustom fctAltCustom);
    public List<FctAltCustom> selectprov(FctAltCustom fctAltCustom);
	//endregion
    public  List<FctAltCustom> selProvname();
    public  List<FctAltCustom> selCreator();
    public  List<FctAltCustom> selAreaName();
    List<FctAltCustom> selAll (FctAltCustomCondition condition);
    public List<FctAltCustom> selectFctAltCustomByChandlestate (FctAltCustomCondition condition, PageBounds of);
    public void updateeventstateByEventid(FctAltCustom fctAltCustom);
}
