
package com.yqjr.fin.risk.stat.condition;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Digits;

import com.yqjr.scfw.common.condition.BaseCondition;

import com.yqjr.fin.risk.stat.entity.ScheduleJob;

public class ScheduleJobCondition extends BaseCondition<ScheduleJob, Long> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/scheduleJob/list
     *表单维护路径：/scheduleJob/form
     *
     */

    /**
     * 任务id
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * bean名称
     */
    @Length(min = 0, max = 100)
    private java.lang.String beanName;

    /**
     * 方法名称
     */
    @Length(min = 0, max = 100)
    private java.lang.String methodName;

    /**
     * 参数
     */
    @Length(min = 0, max = 500)
    private java.lang.String params;

    /**
     * cron表达式
     */
    @Length(min = 0, max = 100)
    private java.lang.String cronExpression;

    /**
     * 任务状态  0：正常  1：暂停
     */
    @Digits(fraction =22,integer=0)
    private Long status;

    /**
     * 备注
     */
    @Length(min = 0, max = 500)
    private java.lang.String remark;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 创建时间
     */
    private java.lang.String createTime;

    /**
     * 最后更新人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 最后更新时间
     */
    private java.lang.String modifyTime;

    /**
     * 执行时间
     */
    @Length(min = 0, max = 250)
    private java.lang.String executionTime;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.lang.String getBeanName() {
        return this.beanName;
    }

    public void setBeanName(java.lang.String beanName) {
        this.beanName = beanName;
    }

    public java.lang.String getMethodName() {
        return this.methodName;
    }

    public void setMethodName(java.lang.String methodName) {
        this.methodName = methodName;
    }

    public java.lang.String getParams() {
        return this.params;
    }

    public void setParams(java.lang.String params) {
        this.params = params;
    }

    public java.lang.String getCronExpression() {
        return this.cronExpression;
    }

    public void setCronExpression(java.lang.String cronExpression) {
        this.cronExpression = cronExpression;
    }

    public Long getStatus() {
        return this.status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public java.lang.String getRemark() {
        return this.remark;
    }

    public void setRemark(java.lang.String remark) {
        this.remark = remark;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public java.lang.String getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.lang.String createTime) {
        this.createTime = createTime;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public java.lang.String getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.lang.String modifyTime) {
        this.modifyTime = modifyTime;
    }

    public java.lang.String getExecutionTime() {
        return this.executionTime;
    }

    public void setExecutionTime(java.lang.String executionTime) {
        this.executionTime = executionTime;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}