package com.yqjr.fin.mkmm.sales.entity;

import com.alibaba.fastjson.annotation.JSONField;
import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;
import java.math.BigDecimal;
import java.util.Date;

public class ActiveMainReview extends BaseEntity<ActiveMainReview> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/activeMainReview/list
     *表单维护路径：/activeMainReview/form
     *
     */

    /**
     * ID
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 活动编码
     */
    @Length(min = 0, max = 20)
    private java.lang.String activeCode;

    /**
     * 活动名称
     */
    @Length(min = 0, max = 64)
    private java.lang.String activeName;

    /**
     * 活动开始日期
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date activeStartime;

    /**
     * 活动截止日期
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date activeEndtime;

    /**
     * 放款开始日期
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date loanStartime;

    /**
     * 放款截止日期
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date loanEndtime;

    /**
     * 首付起始比例
     */
    @Length(min = 0, max = 20)
    private java.lang.String patmentBegin;

    /**
     * 首付终止比例
     */
    @Length(min = 0, max = 20)
    private java.lang.String patmentEnd;

    /**
     * 车籍
     */
    @Length(min = 0, max = 20)
    private java.lang.String carReg;

    /**
     * 贷款期限
     */
    private Long loanTermBegin;

    /**
     * 贷款期限
     */
    private Long loanTermEnd;

    /**
     * 贷款金额
     */
    @Digits(fraction =14,integer=2)
    private BigDecimal loanAmtBegin;

    /**
     * 贷款金额
     */
    @Digits(fraction =14,integer=2)
    private BigDecimal loanAmtEnd;

    /**
     * 促销活动激励标准
     */
    @Digits(fraction =14,integer=2)
    private BigDecimal avtiveCriterion;

    /**
     * 附加贷(0没有，1有)
     */
    @Length(min = 0, max = 20)
    private java.lang.String additionFlag;

    /**
     * 附加贷起始金额
     */
    @Digits(fraction =14,integer=2)
    private BigDecimal additionAmtBegin;

    /**
     * 附加贷终止金额
     */
    @Digits(fraction =14,integer=2)
    private BigDecimal additionAmtEnd;

    /**
     * 活动状态
     */
    @Length(min = 0, max = 20)
    private java.lang.String activeStatus;

    /**
     * 创建时间
     */
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    private java.util.Date modifyTime;

    /**
     * 生效时间
     */
    private java.util.Date startTime;

    /**
     * 附件
     */
    @Length(min = 0, max = 20)
    private java.lang.String annex;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 所属公司
     */
    @Length(min = 0, max = 20)
    private java.lang.String company;

    /**
     * 动支状态
     */
    @Length(min = 0, max = 10)
    private java.lang.String paymentStatus;

    /**
     * 备注
     */
    @Length(min = 0, max = 265)
    private java.lang.String remark;

    /**
     * 活动预计笔数
     */
    @Digits(fraction =22,integer=0)
    private Long expectedCount;

    /**
     * 工作流最新ID
     */
    @Digits(fraction =22,integer=0)
    private Long folowId;

    /**
     * （修改时）取主表中ACTIVE_MAIN_REVIEW_ID
     */
    @Digits(fraction =22,integer=0)
    private Long activeReviewId;

    /**
     * 审核类型（01新增，02修改）
     */
    @Length(min = 0, max = 4)
    private java.lang.String reviewType;

    /**
     * 审核状态（00驳回,01提交审核,02待审核,03审核中,04审核通过）
     */
    @Length(min = 0, max = 4)
    private java.lang.String reviewStatus;

    /**
     * 有效标识（如表记录不删除，以此区分,0无效，1有效）
     */
    @Length(min = 0, max = 10)
    private java.lang.String flag;

    /**
     * 是否导入经销商
     */
    @Length(min = 0, max = 4)
    private java.lang.String inputDeale;

    /**
     * 附件上传ID
     */
    @Length(min = 0, max = 30)
    private java.lang.String additionalId;

    /**
     * 区域编码
     */
    @Length(min = 0, max = 50)
    private java.lang.String areaCode;

    /**
     * 区域名称
     */
    @Length(min = 0, max = 50)
    private java.lang.String areaName;

    /**
     * 区域标识,1为区域，0为省市
     */
    @Length(min = 0, max = 10)
    private java.lang.String inputArea;

    /**
     * 发起人级别,01销售经理,02区域负责人,03市场部人员
     */
    @Length(min = 0, max = 10)
    private java.lang.String founderLevel;

    /**
     * 创建人姓名
     */
    @Length(min = 0, max = 50)
    private java.lang.String creatorName;

    public String getCreatorName() {
        return creatorName;
    }

    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    public String getFounderLevel() {
        return founderLevel;
    }

    public void setFounderLevel(String founderLevel) {
        this.founderLevel = founderLevel;
    }

    public String getInputArea() {
        return inputArea;
    }

    public void setInputArea(String inputArea) {
        this.inputArea = inputArea;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getActiveCode() {
        return activeCode;
    }

    public void setActiveCode(String activeCode) {
        this.activeCode = activeCode;
    }

    public String getActiveName() {
        return activeName;
    }

    public void setActiveName(String activeName) {
        this.activeName = activeName;
    }

    public Date getActiveStartime() {
        return activeStartime;
    }

    public void setActiveStartime(Date activeStartime) {
        this.activeStartime = activeStartime;
    }

    public Date getActiveEndtime() {
        return activeEndtime;
    }

    public void setActiveEndtime(Date activeEndtime) {
        this.activeEndtime = activeEndtime;
    }

    public Date getLoanStartime() {
        return loanStartime;
    }

    public void setLoanStartime(Date loanStartime) {
        this.loanStartime = loanStartime;
    }

    public Date getLoanEndtime() {
        return loanEndtime;
    }

    public void setLoanEndtime(Date loanEndtime) {
        this.loanEndtime = loanEndtime;
    }

    public String getPatmentBegin() {
        return patmentBegin;
    }

    public void setPatmentBegin(String patmentBegin) {
        this.patmentBegin = patmentBegin;
    }

    public String getPatmentEnd() {
        return patmentEnd;
    }

    public void setPatmentEnd(String patmentEnd) {
        this.patmentEnd = patmentEnd;
    }

    public String getCarReg() {
        return carReg;
    }

    public void setCarReg(String carReg) {
        this.carReg = carReg;
    }

    public Long getLoanTermBegin() {
        return loanTermBegin;
    }

    public void setLoanTermBegin(Long loanTermBegin) {
        this.loanTermBegin = loanTermBegin;
    }

    public Long getLoanTermEnd() {
        return loanTermEnd;
    }

    public void setLoanTermEnd(Long loanTermEnd) {
        this.loanTermEnd = loanTermEnd;
    }

    public BigDecimal getLoanAmtBegin() {
        return loanAmtBegin;
    }

    public void setLoanAmtBegin(BigDecimal loanAmtBegin) {
        this.loanAmtBegin = loanAmtBegin;
    }

    public BigDecimal getLoanAmtEnd() {
        return loanAmtEnd;
    }

    public void setLoanAmtEnd(BigDecimal loanAmtEnd) {
        this.loanAmtEnd = loanAmtEnd;
    }

    public BigDecimal getAvtiveCriterion() {
        return avtiveCriterion;
    }

    public void setAvtiveCriterion(BigDecimal avtiveCriterion) {
        this.avtiveCriterion = avtiveCriterion;
    }

    public String getAdditionFlag() {
        return additionFlag;
    }

    public void setAdditionFlag(String additionFlag) {
        this.additionFlag = additionFlag;
    }

    public BigDecimal getAdditionAmtBegin() {
        return additionAmtBegin;
    }

    public void setAdditionAmtBegin(BigDecimal additionAmtBegin) {
        this.additionAmtBegin = additionAmtBegin;
    }

    public BigDecimal getAdditionAmtEnd() {
        return additionAmtEnd;
    }

    public void setAdditionAmtEnd(BigDecimal additionAmtEnd) {
        this.additionAmtEnd = additionAmtEnd;
    }

    public String getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(String activeStatus) {
        this.activeStatus = activeStatus;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public String getAnnex() {
        return annex;
    }

    public void setAnnex(String annex) {
        this.annex = annex;
    }

    public Long getCreator() {
        return creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getExpectedCount() {
        return expectedCount;
    }

    public void setExpectedCount(Long expectedCount) {
        this.expectedCount = expectedCount;
    }

    public Long getFolowId() {
        return folowId;
    }

    public void setFolowId(Long folowId) {
        this.folowId = folowId;
    }

    public Long getActiveReviewId() {
        return activeReviewId;
    }

    public void setActiveReviewId(Long activeReviewId) {
        this.activeReviewId = activeReviewId;
    }

    public String getReviewType() {
        return reviewType;
    }

    public void setReviewType(String reviewType) {
        this.reviewType = reviewType;
    }

    public String getReviewStatus() {
        return reviewStatus;
    }

    public void setReviewStatus(String reviewStatus) {
        this.reviewStatus = reviewStatus;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getAdditionalId() {
        return additionalId;
    }

    public void setAdditionalId(String additionalId) {
        this.additionalId = additionalId;
    }

    public String getInputDeale() {
        return inputDeale;
    }

    public void setInputDeale(String inputDeale) {
        this.inputDeale = inputDeale;
    }
}
