package com.yqjr.fin.mkmm.sales.entity;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;

public class ActiveAreaReview extends BaseEntity<ActiveAreaReview> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/activeAreaReview/list
     *表单维护路径：/activeAreaReview/form
     *
     */

    /**
     * 序列
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 活动审核ID
     */
    @Digits(fraction =22,integer=0)
    private Long activeReviewId;

    /**
     * 活动编号
     */
    @Length(min = 0, max = 32)
    private java.lang.String activeCode;

    /**
     * 序号
     */
    @Digits(fraction =22,integer=0)
    private Long serialNo;

    /**
     * 区域代码
     */
    @Length(min = 0, max = 33)
    private java.lang.String areaCode;

    /**
     * 区域名称
     */
    @Length(min = 0, max = 34)
    private java.lang.String areaName;

    /**
     * 省份代码
     */
    @Length(min = 0, max = 35)
    private java.lang.String provinceCode;

    /**
     * 省份名称
     */
    @Length(min = 0, max = 36)
    private java.lang.String provinceName;

    /**
     * 城市编码
     */
    @Length(min = 0, max = 50)
    private java.lang.String cityCode;

    /**
     * 城市名称
     */
    @Length(min = 0, max = 50)
    private java.lang.String cityName;

    /**
     * 生效时间
     */
    private java.util.Date startTime;

    /**
     * 创建时间
     */
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    private java.util.Date modifyTime;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 所属公司
     */
    @Length(min = 0, max = 20)
    private java.lang.String company;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getActiveReviewId() {
        return this.activeReviewId;
    }

    public void setActiveReviewId(Long activeReviewId) {
        this.activeReviewId = activeReviewId;
    }

    public java.lang.String getActiveCode() {
        return this.activeCode;
    }

    public void setActiveCode(java.lang.String activeCode) {
        this.activeCode = activeCode;
    }

    public Long getSerialNo() {
        return this.serialNo;
    }

    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    public java.lang.String getAreaCode() {
        return this.areaCode;
    }

    public void setAreaCode(java.lang.String areaCode) {
        this.areaCode = areaCode;
    }

    public java.lang.String getAreaName() {
        return this.areaName;
    }

    public void setAreaName(java.lang.String areaName) {
        this.areaName = areaName;
    }

    public java.lang.String getProvinceCode() {
        return this.provinceCode;
    }

    public void setProvinceCode(java.lang.String provinceCode) {
        this.provinceCode = provinceCode;
    }

    public java.lang.String getProvinceName() {
        return this.provinceName;
    }

    public void setProvinceName(java.lang.String provinceName) {
        this.provinceName = provinceName;
    }

    public java.lang.String getCityCode() {
        return this.cityCode;
    }

    public void setCityCode(java.lang.String cityCode) {
        this.cityCode = cityCode;
    }

    public java.lang.String getCityName() {
        return this.cityName;
    }

    public void setCityName(java.lang.String cityName) {
        this.cityName = cityName;
    }

    public java.util.Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public java.lang.String getCompany() {
        return this.company;
    }

    public void setCompany(java.lang.String company) {
        this.company = company;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
