package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.ActiveMatchMainCondition;
import com.yqjr.fin.mkmm.sales.rest.vo.fee.ActiveMatchMainVo;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.ActiveMatchMain;
import com.yqjr.scfw.common.pagination.model.PageBounds;

import java.util.List;

public interface ActiveMatchMainMapper extends Mapper<ActiveMatchMain, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    /**
     * 创建活动费用结算单   并进入审核流程
     * create by fanna on 20180605
     */
    List<ActiveMatchMain> selectActiveMatchByCode(String businessCode,String company);

    /**
     * 活动结算列表页面加载数据
     * @param condition
     * @param pageBounds
     * @return
     */
    List<ActiveMatchMainVo> selectQueryList(ActiveMatchMainCondition condition, PageBounds... pageBounds);
}
