package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.PersonCityReview;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PersonCityReviewMapper extends Mapper<PersonCityReview, Long> {


    //region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
    void deleteByPersonCode(@Param("personCode") String personCode);

    void insertOneSelected(PersonCityReview personCityReview);
}
