package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.PersonMainReviewCondition;
import com.yqjr.fin.mkmm.sales.condition.PersonWorkCondition;
import com.yqjr.fin.mkmm.sales.entity.BrandMain;
import com.yqjr.fin.mkmm.sales.entity.PersonMainReview;
import com.yqjr.fin.mkmm.sales.entity.TeamMain;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonMainReviewProcessVo;
import com.yqjr.fin.mkmm.sales.vo.domin.PersonMainReviewVo;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.scfw.common.pagination.model.PageBounds;

import java.util.List;

//import com.yqjr.fin.mkmm.sales.model.PersonDetail;

public interface PersonMainReviewMapper extends Mapper<PersonMainReview, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    List<PersonMainReviewVo> selectPersonReviewList(PersonWorkCondition condition);
    List<PersonMainReviewVo> selectPersonReviewTable(PersonWorkCondition condition, PageBounds... pageBounds);//查询审核人员列表
    PersonMainReviewVo selectPersonReviewByPersonCode(String personCode);//通过人员代码查询人员信息
    List<TeamMain> selectTeamByAreaOfPerson(String areaCode);//通过人员所在区域查询团队
    List<BrandMain> selectBrands();//品牌

    List<PersonMainReviewProcessVo> selectPersonReviewProcessList(PersonWorkCondition condition,PageBounds pageBounds);
    List<PersonMainReviewVo> selectPersonReviewProcessDetail(String personCode);

    Integer updateByPersonCodeAndId(PersonMainReview personMainReview);
    //endregion

    /**
     * 人员审核页面模糊查询
     * @param personMainReviewCondition
     * @return
     * create by liufang 2018/6/23
     */
    List<PersonMainReview> queryPersonMainReviewList(PersonMainReviewCondition personMainReviewCondition);

    /**
     *  主从表通过人员团队审核表id关联
     *  更改人员城市和品牌表数据存储方式
     *  update by fannaian on 20180808
     * @param personTeamReviewId
     * @return
     */
    PersonMainReviewVo selectPersonReviewById(Long personTeamReviewId);
}
