package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.PlanTrackYear;

import java.util.List;

public interface PlanTrackYearMapper extends Mapper<PlanTrackYear, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

    //当前月数据数据进入轨迹表
    List<PlanTrackYear> selectPlanTrackYear(String year,String company);
    //根据年删除数据
    void deletePlanTrackYear(String year,String company);
}
