package com.yqjr.fin.mkmm.sales.mapper;

import com.yqjr.fin.mkmm.sales.condition.WorkFlowCondition;
import com.yqjr.scfw.common.condition.BaseCondition;
import com.yqjr.scfw.common.mapper.Mapper;
import com.yqjr.fin.mkmm.sales.entity.WorkFlow;
import com.yqjr.scfw.common.pagination.model.PageBounds;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WorkFlowMapper extends Mapper<WorkFlow, Long> {

	//region generated by CodeRobot
    
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	//~此线上方代码自动生成，在此下方编写自定义代码。
	//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion


    /**
     * 查审核进度
     * create by fnana
     * @param condition
     * @param pageBounds
     * @return
     */
    List<WorkFlow> selectWorkFlow(WorkFlowCondition condition, PageBounds... pageBounds);

    /**
     * 根据ActiveMainReview表的ID，查询工作流信息
     * @param mid
     * @return
     */
    WorkFlow selectByActiveMainId(@Param("mid") Long mid);

    Long selectActiveIDById(@Param("mid") Long mid);

    void updateStatusById(@Param("status") String status,@Param("flowId") Long flowId,@Param("modifier") Long modifier);
}
