package com.yqjr.fin.scfw.meta.entity;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;

public class Organization extends BaseEntity<Organization> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/organization/list
     *表单维护路径：/organization/form
     *
     */

    /**
     * 主键
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 组织机构号
     */
    @Length(min = 0, max = 30)
    private java.lang.String organizationno;

    /**
     * 组织机构名称
     */
    @Length(min = 0, max = 100)
    private java.lang.String organizationname;

    /**
     * 组织机构类型
     */
    @Length(min = 0, max = 2)
    private java.lang.String organizationtype;

    /**
     * 父组织机构号
     */
    @Length(min = 0, max = 30)
    private java.lang.String superorganizationno;

    /**
     * 组织机构代码后两位
     */
    @Length(min = 0, max = 2)
    private java.lang.String organizationcode;

    /**
     * 客户id
     */
    @Digits(fraction =22,integer=0)
    private Long customerid;

    /**
     * 状态(1有效,-1无效)
     */
    @Digits(fraction =22,integer=0)
    private Long status;

    /**
     * 直客合同号生成简写 如CC ,SZ,BJ等
     */
    @Length(min = 0, max = 20)
    private java.lang.String simplename;

    /**
     * 录入人id
     */
    @Digits(fraction =22,integer=0)
    private Long inputuserid;

    /**
     * 类型
     */
    @Digits(fraction =22,integer=0)
    private Long type;

    /**
     * 类别
     */
    @Digits(fraction =22,integer=0)
    private Long ctype;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 创建时间
     */
    private java.lang.String createTime;

    /**
     * 最后更新人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 最后更新时间
     */
    private java.lang.String modifyTime;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.lang.String getOrganizationno() {
        return this.organizationno;
    }

    public void setOrganizationno(java.lang.String organizationno) {
        this.organizationno = organizationno;
    }

    public java.lang.String getOrganizationname() {
        return this.organizationname;
    }

    public void setOrganizationname(java.lang.String organizationname) {
        this.organizationname = organizationname;
    }

    public java.lang.String getOrganizationtype() {
        return this.organizationtype;
    }

    public void setOrganizationtype(java.lang.String organizationtype) {
        this.organizationtype = organizationtype;
    }

    public java.lang.String getSuperorganizationno() {
        return this.superorganizationno;
    }

    public void setSuperorganizationno(java.lang.String superorganizationno) {
        this.superorganizationno = superorganizationno;
    }

    public java.lang.String getOrganizationcode() {
        return this.organizationcode;
    }

    public void setOrganizationcode(java.lang.String organizationcode) {
        this.organizationcode = organizationcode;
    }

    public Long getCustomerid() {
        return this.customerid;
    }

    public void setCustomerid(Long customerid) {
        this.customerid = customerid;
    }

    public Long getStatus() {
        return this.status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public java.lang.String getSimplename() {
        return this.simplename;
    }

    public void setSimplename(java.lang.String simplename) {
        this.simplename = simplename;
    }

    public Long getInputuserid() {
        return this.inputuserid;
    }

    public void setInputuserid(Long inputuserid) {
        this.inputuserid = inputuserid;
    }

    public Long getType() {
        return this.type;
    }

    public void setType(Long type) {
        this.type = type;
    }

    public Long getCtype() {
        return this.ctype;
    }

    public void setCtype(Long ctype) {
        this.ctype = ctype;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public java.lang.String getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.lang.String createTime) {
        this.createTime = createTime;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public java.lang.String getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.lang.String modifyTime) {
        this.modifyTime = modifyTime;
    }

}
