
package com.yqjr.fin.mkmm.sales.condition;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Digits;

import com.yqjr.scfw.common.condition.BaseCondition;

import com.yqjr.fin.mkmm.sales.entity.MaterialOut;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class MaterialOutCondition extends BaseCondition<MaterialOut, Long> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/materialOut/list
     *表单维护路径：/materialOut/form
     *
     */

    /**
     * 序号
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 素材类型编码
     */
    @Length(min = 0, max = 20)
    private String materialCode;

    /**
     * 素菜类型名称
     */
    @Length(min = 0, max = 100)
    private String materialName;

    /**
     * 素材主题
     */
    @Length(min = 0, max = 100)
    private String materialTheme;

    /**
     * 适用品牌编码
     */
    @Length(min = 0, max = 20)
    private String brandsCode;

    /**
     * 适用品牌名称
     */
    @Length(min = 0, max = 100)
    private String brandsName;

    /**
     * 素材描述
     */
    @Length(min = 0, max = 530)
    private String materialDescription;

    /**
     * 上传附件id 生成的id，送至影像平台
     */
    @Length(min = 0, max = 30)
    private String appendixId;

    /**
     * 有效期开始时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date effectiveStartTime;

    /**
     * 有效期结束时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date effectiveEndTime;

    /**
     * 推送区域名称
     */
    @Length(min = 0, max = 100)
    private String areaName;

    /**
     * 推送区域代码
     */
    @Length(min = 0, max = 20)
    private String areaCode;

    /**
     * 素材来源
     */
    @Length(min = 0, max = 100)
    private String materialSource;

    /**
     * 接收时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date receiveTime;

    /**
     * 经销商反馈意见
     */
    @Length(min = 0, max = 530)
    private String opinion;

    /**
     * 接收状态0：未接收，1：已接收
     */
    @Length(min = 0, max = 2)
    private String receiveStatus;

    /**
     * 公司1 ：汽车金融 ，2：租赁公司
     */
    @Length(min = 0, max = 2)
    private String company;

    /**
     * 创建时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private java.util.Date modifyTime;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 素材创建人
     */
    @Length(min = 0, max = 20)
    private String uploader;
    /**
     * 素材上传表id
     */
    @Digits(fraction =22,integer=0)
    private Long inId;

    public Long getInId() {
        return inId;
    }

    public void setInId(Long inId) {
        this.inId = inId;
    }

    public String getUploader() {
        return uploader;
    }

    public void setUploader(String uploader) {
        this.uploader = uploader;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMaterialCode() {
        return this.materialCode;
    }

    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode;
    }

    public String getMaterialName() {
        return this.materialName;
    }

    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }

    public String getMaterialTheme() {
        return this.materialTheme;
    }

    public void setMaterialTheme(String materialTheme) {
        this.materialTheme = materialTheme;
    }

    public String getBrandsCode() {
        return this.brandsCode;
    }

    public void setBrandsCode(String brandsCode) {
        this.brandsCode = brandsCode;
    }

    public String getBrandsName() {
        return this.brandsName;
    }

    public void setBrandsName(String brandsName) {
        this.brandsName = brandsName;
    }

    public String getMaterialDescription() {
        return this.materialDescription;
    }

    public void setMaterialDescription(String materialDescription) {
        this.materialDescription = materialDescription;
    }

    public String getAppendixId() {
        return this.appendixId;
    }

    public void setAppendixId(String appendixId) {
        this.appendixId = appendixId;
    }

    public Date getEffectiveStartTime() {
        return this.effectiveStartTime;
    }

    public void setEffectiveStartTime(Date effectiveStartTime) {
        this.effectiveStartTime = effectiveStartTime;
    }

    public Date getEffectiveEndTime() {
        return this.effectiveEndTime;
    }

    public void setEffectiveEndTime(Date effectiveEndTime) {
        this.effectiveEndTime = effectiveEndTime;
    }

    public String getAreaName() {
        return this.areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getAreaCode() {
        return this.areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getMaterialSource() {
        return this.materialSource;
    }

    public void setMaterialSource(String materialSource) {
        this.materialSource = materialSource;
    }

    public Date getReceiveTime() {
        return this.receiveTime;
    }

    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    public String getOpinion() {
        return this.opinion;
    }

    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }

    public String getReceiveStatus() {
        return this.receiveStatus;
    }

    public void setReceiveStatus(String receiveStatus) {
        this.receiveStatus = receiveStatus;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}