package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeAreaReview")
public class ActiveAreaReviewController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activeareareview/activeAreaReviewList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activeareareview/activeAreaReviewView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activeareareview/activeAreaReviewForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activeareareview/activeAreaReviewModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activeareareview/activeAreaReviewModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activeareareview/activeAreaReviewListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}