package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeCarHis")
public class ActiveCarHisController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activecarhis/activeCarHisList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activecarhis/activeCarHisView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activecarhis/activeCarHisForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activecarhis/activeCarHisModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activecarhis/activeCarHisModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activecarhis/activeCarHisListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}