package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/personCityReview")
public class PersonCityReviewController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/personcityreview/personCityReviewList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/personcityreview/personCityReviewView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/personcityreview/personCityReviewForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/personcityreview/personCityReviewModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/personcityreview/personCityReviewModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/personcityreview/personCityReviewListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}