package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.ActiveArea;
import com.yqjr.fin.mkmm.sales.mapper.ActiveAreaMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class ActiveAreaService extends BaseService<ActiveAreaMapper, ActiveArea, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
    @Autowired
    private ActiveAreaMapper activeAreaMapper;

    /**
     * 根据code查活动区域
     * create by fanna 20180604
     * @return
     */
    public List<ActiveArea> selectActiveAreaByCode(String activeCode,String company){

        return activeAreaMapper.selectActiveAreaByCode(activeCode,company);
    }

    public void patchByActiveCode(ActiveArea activeArea) {
        activeAreaMapper.patchByActiveCode(activeArea);
    }
}