package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.PersonBrand;
import com.yqjr.fin.mkmm.sales.mapper.PersonBrandMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional(readOnly = true)
public class PersonBrandService extends BaseService<PersonBrandMapper, PersonBrand, Long> {

    @Autowired
    private PersonBrandMapper personBrandMapper;
    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    /**
     * 根据人员代码更新人员城市表
     * @return
     */
    public int patchByPersonCode(PersonBrand personBrand){
        return personBrandMapper.patchByPersonCode(personBrand);
    }
    //endregion
}