package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.condition.ActiveMatchMainCondition;
import com.yqjr.fin.mkmm.sales.rest.vo.fee.ActiveMatchMainVo;
import com.yqjr.scfw.common.pagination.model.PageBounds;
import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.ActiveMatchMain;
import com.yqjr.fin.mkmm.sales.mapper.ActiveMatchMainMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class ActiveMatchMainService extends BaseService<ActiveMatchMainMapper, ActiveMatchMain, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion

    @Autowired
    private ActiveMatchMainMapper activeMatchMainMapper;

    /**
     * 创建活动费用结算单   并进入审核流程
     * create by fanna on 20180605
     */
    public List<ActiveMatchMain> selectActiveMatchByCode(String businessCode,String company){

        return activeMatchMainMapper.selectActiveMatchByCode(businessCode,company);
    }

    /**
     * 活动结算列表页面加载数据
     * @param condition
     * @param pageBounds
     * @return
     */
    public  List<ActiveMatchMainVo> selectQueryList(ActiveMatchMainCondition condition, PageBounds... pageBounds){
        return activeMatchMainMapper.selectQueryList(condition,pageBounds);
    }

}