package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.ActiveMarketing;
import com.yqjr.fin.mkmm.sales.mapper.ActiveMarketingMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class ActiveMarketingService extends BaseService<ActiveMarketingMapper, ActiveMarketing, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion

    @Autowired
    private ActiveMarketingMapper activeMarketingMapper;

    /**
     * 根据code查活动营销活动
     * create by fanna 20180604
     * @return
     */
    public List<ActiveMarketing> selectActiveMarketingByCode(String activeCode,String company) {

        return activeMarketingMapper.selectActiveMarketingByCode(activeCode,company);
    }

    public void patchByActiveCode(ActiveMarketing newActiveMarketing) {
        activeMarketingMapper.patchByActiveCode(newActiveMarketing);
    }
}