package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.ActiveDealer;
import com.yqjr.fin.mkmm.sales.mapper.ActiveDealerMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class ActiveDealerService extends BaseService<ActiveDealerMapper, ActiveDealer, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion

    @Autowired
    private ActiveDealerMapper activeDealerMapper;

    /**
     * 根据code查活动经销商
     * create by fanna 20180604
     * @return
     */
    public List<ActiveDealer> selectActiveDealeByCode(String activeCode,String company){

        return activeDealerMapper.selectActiveDealeByCode(activeCode,company);
    }

    public void deleteByActiveCode(String activeCode) {
        activeDealerMapper.deleteByActiveCode(activeCode);
    }
}