package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.ActiveAddition;
import com.yqjr.fin.mkmm.sales.mapper.ActiveAdditionMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class ActiveAdditionService extends BaseService<ActiveAdditionMapper, ActiveAddition, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion

    @Autowired
    private ActiveAdditionMapper activeAdditionMapper;

    /**
     * 根据code查活动附加贷
     * create by fanna 20180604
     * @return
     */
    public List<ActiveAddition> selectActiveAdditionalByCode(String activeCode,String company){

        return activeAdditionMapper.selectActiveAdditionalByCode(activeCode,company);
    }

    public void patchByActiveCode(ActiveAddition activeAddition) {
        activeAdditionMapper.patchByActiveCode(activeAddition);
    }
}