package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.entity.DealerSale;
import com.yqjr.fin.mkmm.sales.mapper.DealerSaleMapper;
import com.yqjr.scfw.common.service.BaseService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;
import java.util.List;

@Service
@Transactional(readOnly = true)
public class DealerSaleService extends BaseService<DealerSaleMapper, DealerSale, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion

    @Autowired DealerSaleMapper dealerSaleMapper;

    //根据日期查询数每日数据
    public List<DealerSale> selectDataByDate(Date date) {
        List<DealerSale> dealerSales = dealerSaleMapper.selectDataByDate(date);
        return dealerSales;
    }
}