package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.condition.EventTeamCondition;
import com.yqjr.scfw.common.pagination.model.PageBounds;
import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.EventTeam;
import com.yqjr.fin.mkmm.sales.mapper.EventTeamMapper;
import com.yqjr.scfw.common.session.SessionHolder;
import com.yqjr.scfw.common.session.UserContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class EventTeamService extends BaseService<EventTeamMapper, EventTeam, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion

    @Autowired
    private EventTeamMapper eventTeamMapper;

    //综合查询，查团队重大事件
    public List<EventTeam> queryTeamEventByCode(String teamCode){
        UserContext userContext=SessionHolder.getUserContext();
        String company = userContext.getComCode();
        List<EventTeam> eventTeams = eventTeamMapper.queryTeamEventByCode(teamCode,company );
        return eventTeams;
    }



    /**
     * 模糊查询团队重大事件
     */
    public List<EventTeam> queryEventTeam(EventTeamCondition eventTeamCondition, PageBounds... pageBounds){
        List<EventTeam> eventTeams =null;
        eventTeams=eventTeamMapper.queryEventTeam(eventTeamCondition,pageBounds);
        return eventTeams;
    }

    /**
     * 添加重大团队权限
     * @param
     * @return
     */
    public List<EventTeam> queryTeamMainByName(String teamName,String company){

        return eventTeamMapper.queryTeamMainByName(teamName,company);
    }

}