package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.entity.PersonMainHis;
import com.yqjr.fin.mkmm.sales.mapper.PersonMainHisMapper;
import com.yqjr.fin.mkmm.sales.mapper.PersonTeamReviewMapper;
import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.PersonTeamReview;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class PersonTeamReviewService extends BaseService<PersonTeamReviewMapper, PersonTeamReview, Long> {

    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    @Autowired
    private  PersonTeamReviewMapper personTeamReviewMapper;

    @Autowired
    private PersonMainHisMapper personMainHisMapper;

    /**
     * 查询系统中人员是否被引入
     * @param searchPerson  登录用户名
     * @return
     */
    public List<PersonTeamReview> getPersonTeamReviewByPersonCode(String searchPerson){
        PersonTeamReview personTeamReview;
        List<PersonTeamReview> list=personTeamReviewMapper.selectByPersonCode(searchPerson);
        return  list;
    }

    /**
     * 查询人员基本信息变更
     * @param  personCode  人员代码
     * @return
     */
    public List<PersonMainHis> selectPersonTeamReviewByPersonCode(String personCode){
        List<PersonMainHis> list=personMainHisMapper.selectPersonMainHisByCode(personCode);
        return  list;
    }

    //endregion



}