package com.yqjr.fin.mkmm.sales.services;

import com.yqjr.fin.mkmm.sales.condition.ProductCodeCondition;
import com.yqjr.scfw.common.service.BaseService;
import com.yqjr.fin.mkmm.sales.entity.ProductCode;
import com.yqjr.fin.mkmm.sales.mapper.ProductCodeMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.sound.midi.Soundbank;
import java.util.List;

@Service
@Transactional(readOnly = true)
public class ProductCodeService extends BaseService<ProductCodeMapper, ProductCode, Long> {

    @Autowired
    private ProductCodeMapper productCodeMapper;

    public List<ProductCode> select(ProductCodeCondition condition){
        return productCodeMapper.select(condition);
    };

    public List<ProductCode> selectByCondition(String vdictcode) {
        return productCodeMapper.selectByCondition(vdictcode);
    }
    //region generated by CodeRobot

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}