package com.yqjr.fin.mkmm.sales.entity;

import com.alibaba.fastjson.annotation.JSONField;
import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;

public class TeamReview extends BaseEntity<TeamReview> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/teamReview/list
     *表单维护路径：/teamReview/form
     *
     */

    /**
     * 序列
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 区域代码
     */
    @Length(min = 0, max = 30)
    private String areaCode;

    /**
     * 区域名称
     */
    @Length(min = 0, max = 128)
    private String areaName;

    /**
     * 团队代码
     */
    @Length(min = 0, max = 30)
    private String teamCode;

    /**
     * 团队名称
     */
    @Length(min = 0, max = 128)
    private String teamName;

    /**
     * 团队等级（01一级，02二级，03三级）
     */
    @Length(min = 0, max = 64)
    private String teamLevel;

    /**
     * 团队类型（01普通）
     */
    @Length(min = 0, max = 30)
    private String teamType;

    /**
     * 团队状态(0 无效,1 有效)
     */
    @Length(min = 0, max = 30)
    private String teamStatus;

    /**
     * 团队负责人
     */
    @Length(min = 0, max = 30)
    private String teamLeader;

    /**
     * 联系电话
     */
    @Length(min = 0, max = 30)
    private String teamPhone;

    /**
     * 邮编
     */
    @Length(min = 0, max = 30)
    private String teamZip;

    /**
     * 地址
     */
    @Length(min = 0, max = 128)
    private String teamAddress;

    /**
     * 传真
     */
    @Length(min = 0, max = 30)
    private String teamFax;

    /**
     * 生效时间
     */
    @JSONField(format="yyyy-MM-dd")
    private java.util.Date startTime;

    /**
     * 创建时间
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    private java.util.Date modifyTime;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 备注
     */
    @Length(min = 0, max = 530)
    private String remark;

    /**
     * 审核状态（00驳回,01提交审核,02待审核,03审核中，04审核通过）
     */
    @Length(min = 0, max = 30)
    private String reviewStatus;

    /**
     * 有效标识（如表记录不删除，以此区分,0无效，1有效）
     */
    @Length(min = 0, max = 30)
    private String flag;

    /**
     * 备用字段1
     */
    @Length(min = 0, max = 256)
    private String transcode1;

    /**
     * 备用字段2
     */
    @Length(min = 0, max = 256)
    private String transcode2;

    /**
     * 备用字段3
     */
    @Length(min = 0, max = 256)
    private String transcode3;

    /**
     * 备用字段4
     */
    @Length(min = 0, max = 256)
    private String transcode4;

    /**
     * 操作类型（01新增，02修改）
     */
    @Length(min = 0, max = 30)
    private String reviewType;

    /**
     * 工作流id
     */
    @Digits(fraction =22,integer=0)
    private Long flowId;
    /**
     * 创建人名称
     */
    @Length(min = 0, max = 50)
    private java.lang.String createName;

    /**
     * 公司
     */
    @Length(min = 0, max = 20)
    private java.lang.String company;

    /**
     * 发起人级别,01销售经理,02区域负责人,03市场部人员
     */
    @Length(min = 0, max = 10)
    private java.lang.String founderLevel;

    public String getFounderLevel() {
        return founderLevel;
    }

    public void setFounderLevel(String founderLevel) {
        this.founderLevel = founderLevel;
    }

    public java.lang.String getCompany() {
        return this.company;
    }

    public void setCompany(java.lang.String company) {
        this.company = company;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAreaCode() {
        return this.areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getAreaName() {
        return this.areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getTeamCode() {
        return this.teamCode;
    }

    public void setTeamCode(String teamCode) {
        this.teamCode = teamCode;
    }

    public String getTeamName() {
        return this.teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    public String getTeamLevel() {
        return this.teamLevel;
    }

    public void setTeamLevel(String teamLevel) {
        this.teamLevel = teamLevel;
    }

    public String getTeamType() {
        return this.teamType;
    }

    public void setTeamType(String teamType) {
        this.teamType = teamType;
    }

    public String getTeamStatus() {
        return this.teamStatus;
    }

    public void setTeamStatus(String teamStatus) {
        this.teamStatus = teamStatus;
    }

    public String getTeamLeader() {
        return this.teamLeader;
    }

    public void setTeamLeader(String teamLeader) {
        this.teamLeader = teamLeader;
    }

    public String getTeamPhone() {
        return this.teamPhone;
    }

    public void setTeamPhone(String teamPhone) {
        this.teamPhone = teamPhone;
    }

    public String getTeamZip() {
        return this.teamZip;
    }

    public void setTeamZip(String teamZip) {
        this.teamZip = teamZip;
    }

    public String getTeamAddress() {
        return this.teamAddress;
    }

    public void setTeamAddress(String teamAddress) {
        this.teamAddress = teamAddress;
    }

    public String getTeamFax() {
        return this.teamFax;
    }

    public void setTeamFax(String teamFax) {
        this.teamFax = teamFax;
    }

    public java.util.Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getReviewStatus() {
        return this.reviewStatus;
    }

    public void setReviewStatus(String reviewStatus) {
        this.reviewStatus = reviewStatus;
    }

    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getTranscode1() {
        return this.transcode1;
    }

    public void setTranscode1(String transcode1) {
        this.transcode1 = transcode1;
    }

    public String getTranscode2() {
        return this.transcode2;
    }

    public void setTranscode2(String transcode2) {
        this.transcode2 = transcode2;
    }

    public String getTranscode3() {
        return this.transcode3;
    }

    public void setTranscode3(String transcode3) {
        this.transcode3 = transcode3;
    }

    public String getTranscode4() {
        return this.transcode4;
    }

    public void setTranscode4(String transcode4) {
        this.transcode4 = transcode4;
    }

    public String getReviewType() {
        return this.reviewType;
    }

    public void setReviewType(String reviewType) {
        this.reviewType = reviewType;
    }

    public Long getFlowId() {
        return flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public java.lang.String getCreateName() {
        return this.createName;
    }

    public void setCreateName(java.lang.String createName) {
        this.createName = createName;
    }


    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //
}
