package com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-06-07T15:04:56.753+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://service.selectbillcreatestatusimpl.server.expense.yqjr.webservice.cc.epoch.com/", name = "SelectBillCreateStatusService")
@XmlSeeAlso({ObjectFactory.class})
public interface SelectBillCreateStatusService {

    @WebMethod
    @RequestWrapper(localName = "selectBillCreateStatusMethod", targetNamespace = "http://service.selectbillcreatestatusimpl.server.expense.yqjr.webservice.cc.epoch.com/", className = "com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl.SelectBillCreateStatusMethod")
    @ResponseWrapper(localName = "selectBillCreateStatusMethodResponse", targetNamespace = "http://service.selectbillcreatestatusimpl.server.expense.yqjr.webservice.cc.epoch.com/", className = "com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl.SelectBillCreateStatusMethodResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl.BillStatusVO> selectBillCreateStatusMethod(
            @WebParam(name = "requestCommon", targetNamespace = "")
            com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl.RequestCommon requestCommon,
            @WebParam(name = "billStatusList", targetNamespace = "")
            java.util.List<com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl.BillStatusVO> billStatusList
    ) throws Exception_Exception;
}
