package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeMatchDetail")
public class ActiveMatchDetailController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activematchdetail/activeMatchDetailList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activematchdetail/activeMatchDetailView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activematchdetail/activeMatchDetailForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activematchdetail/activeMatchDetailModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activematchdetail/activeMatchDetailModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activematchdetail/activeMatchDetailListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}