package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeBusiness")
public class ActiveBusinessController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activebusiness/activeBusinessList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activebusiness/activeBusinessView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activebusiness/activeBusinessForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activebusiness/activeBusinessModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activebusiness/activeBusinessModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activebusiness/activeBusinessListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}