package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/activeProdHis")
public class ActiveProdHisController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/activeprodhis/activeProdHisList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/activeprodhis/activeProdHisView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/activeprodhis/activeProdHisForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/activeprodhis/activeProdHisModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/activeprodhis/activeProdHisModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/activeprodhis/activeProdHisListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}