package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping(value = "/personMainReview")
public class PersonMainReviewController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/personmainreview/personMainReviewList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/personmainreview/personMainReviewView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/personmainreview/personMainReviewForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() { return "framework/system/personmainreview/personMainReviewModify"; }

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/personmainreview/personMainReviewModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/personmainreview/personMainReviewListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion

	/**
	 * 人员审核进度处理列表
	 * @return
	 */
	@RequestMapping(value = "/processlist")
	public String processList() {
		return "framework/system/personmainreview/personMainReviewProcessList";
	}

	/**
	 * 人员审核进度处理查看
	 * @return
	 */
	@RequestMapping(value = "/processview")
	public String processview() {
		return "framework/system/personmainreview/personMainReviewProcessView";
	}

    /**
     * 人员审核进度处理修改
     * @return
     */
    @RequestMapping(value = "/processmodify")
    public String processmodify() {
        return "framework/system/personmainreview/personMainReviewProcessModify";
    }
}