package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/personSale")
public class PersonSaleController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/personsale/personSaleList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/personsale/personSaleView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/personsale/personSaleForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/personsale/personSaleModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/personsale/personSaleModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/personsale/personSaleListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}