package com.yqjr.fin.mkmm.sales.ui.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = "/productCode")
public class ProductCodeController {

	//region generated by CodeRobot
	
	@RequestMapping(value = "/list")
	public String list() {
		return "framework/system/productcode/productCodeList";
	}

    @RequestMapping(value = "/view")
    public String view() {
        return "framework/system/productcode/productCodeView";
    }

	@RequestMapping(value = "/form")
	public String form() {
		return "framework/system/productcode/productCodeForm";
	}
	
	@RequestMapping(value = "/modify")
	public String modify() {
		return "framework/system/productcode/productCodeModify";
	}

	@RequestMapping(value = "/modal")
	public String modal() {
		return "framework/system/productcode/productCodeModal";
	}

	@RequestMapping(value = "/listModal")
	public String listModal() {
		return "framework/system/productcode/productCodeListModal";
	}
	
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~此线上方代码自动生成，在此下方编写自定义代码。
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	//endregion
}