package com.yqjr.fin.mkmm.sales.entity;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;

public class DetTeam extends BaseEntity<DetTeam> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/detTeam/list
     *表单维护路径：/detTeam/form
     *
     */

    /**
     * 序列
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 团队代码
     */
    @Length(min = 0, max = 32)
    private String teamCode;

    /**
     * 团队名称
     */
    @Length(min = 0, max = 50)
    private String teamName;

    /**
     * 年
     */
    @Length(min = 0, max = 4)
    private String year;

    /**
     * 月
     */
    @Length(min = 0, max = 4)
    private String month;

    /**
     * 品牌
     */
    @Length(min = 0, max = 4)
    private String brands;

    /**
     * 一月
     */
    @Digits(fraction =22,integer=0)
    private Long january;

    /**
     * 二月
     */
    @Digits(fraction =22,integer=0)
    private Long february;

    /**
     * 三月
     */
    @Digits(fraction =22,integer=0)
    private Long march;

    /**
     * 四月
     */
    @Digits(fraction =22,integer=0)
    private Long april;

    /**
     * 五月
     */
    @Digits(fraction =22,integer=0)
    private Long may;

    /**
     * 六月
     */
    @Digits(fraction =22,integer=0)
    private Long june;

    /**
     * 七月
     */
    @Digits(fraction =22,integer=0)
    private Long jule;

    /**
     * 八月
     */
    @Digits(fraction =22,integer=0)
    private Long august;

    /**
     * 九月
     */
    @Digits(fraction =22,integer=0)
    private Long september;

    /**
     * 十月
     */
    @Digits(fraction =22,integer=0)
    private Long october;

    /**
     * 十一月
     */
    @Digits(fraction =22,integer=0)
    private Long november;

    /**
     * 十二月
     */
    @Digits(fraction =22,integer=0)
    private Long december;

    /**
     * 创建时间
     */
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    private java.util.Date modifyTime;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTeamCode() {
        return this.teamCode;
    }

    public void setTeamCode(String teamCode) {
        this.teamCode = teamCode;
    }

    public String getTeamName() {
        return this.teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getMonth() {
        return this.month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public String getBrands() {
        return this.brands;
    }

    public void setBrands(String brands) {
        this.brands = brands;
    }

    public Long getJanuary() {
        return this.january;
    }

    public void setJanuary(Long january) {
        this.january = january;
    }

    public Long getFebruary() {
        return this.february;
    }

    public void setFebruary(Long february) {
        this.february = february;
    }

    public Long getMarch() {
        return this.march;
    }

    public void setMarch(Long march) {
        this.march = march;
    }

    public Long getApril() {
        return this.april;
    }

    public void setApril(Long april) {
        this.april = april;
    }

    public Long getMay() {
        return this.may;
    }

    public void setMay(Long may) {
        this.may = may;
    }

    public Long getJune() {
        return this.june;
    }

    public void setJune(Long june) {
        this.june = june;
    }

    public Long getJule() {
        return this.jule;
    }

    public void setJule(Long jule) {
        this.jule = jule;
    }

    public Long getAugust() {
        return this.august;
    }

    public void setAugust(Long august) {
        this.august = august;
    }

    public Long getSeptember() {
        return this.september;
    }

    public void setSeptember(Long september) {
        this.september = september;
    }

    public Long getOctober() {
        return this.october;
    }

    public void setOctober(Long october) {
        this.october = october;
    }

    public Long getNovember() {
        return this.november;
    }

    public void setNovember(Long november) {
        this.november = november;
    }

    public Long getDecember() {
        return this.december;
    }

    public void setDecember(Long december) {
        this.december = december;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
