management:
  security:
    enabled: false
spring:
  cloud:
    datasource:
      name: test
      url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.20.130.130)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.20.130.132)(PORT=1521)))(LOAD_BALANCE = yes)(FAILOVER = ON)(CONNECT_DATA=(SERVICE_NAME=PROD)(FAILOVER_MODE=(TYPE = SELECT)(METHOD = BASIC)(RETIRES = 5)(DELAY = 5))))
      username: mkmm
      password: af_mkmm_i8
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.OracleDriver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#  activiti:
#    database-schema: eco #数据库名称
#    database-schema-update: none #数据库中没有表时会新建
#    check-process-definitions: false #是否检测流程定义文件
#    async-executor-activate: false
#    async-executor-enabled: false
mybatis:
  type-aliases-package: com.yqjr.fin.scfw.isomer.entity
  basepackage: com.yqjr.fin.scfw.isomer.mapper
  mapper-locations: classpath:mapper/**/*.xml
  xmlLocation: ${mybatis.mapper-locations}

#存储配置
#fileStorage:
  #本地存储
  #type: local
  #local:
  #   dir: c:/storage

  #FastDFS配置
#  type: fastdfs
#  fastdfs:
#    connect_timeout_in_seconds: 5
#    network_timeout_in_seconds: 30
#    charset: UTF-8
#    http_anti_steal_token: false
#    http_secret_key: FastDFS1234567890
#    http_tracker_http_port: 80
#    tracker_servers: 10.21.120.82:22122

