
package com.yqjr.fin.mkmm.sales.condition;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Digits;

import com.yqjr.scfw.common.condition.BaseCondition;

import com.yqjr.fin.mkmm.sales.entity.ActiveCarReview;

public class ActiveCarReviewCondition extends BaseCondition<ActiveCarReview, Long> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/activeCarReview/list
     *表单维护路径：/activeCarReview/form
     *
     */

    /**
     * 序列
     */
    @Digits(fraction =22,integer=0)
    private Long id;

    /**
     * 活动审核ID
     */
    @Digits(fraction =22,integer=0)
    private Long activeReviewId;

    /**
     * 活动编号
     */
    @Length(min = 0, max = 32)
    private java.lang.String activeCode;

    /**
     * 序号
     */
    @Digits(fraction =22,integer=0)
    private Long serialNo;

    /**
     * 品牌编码
     */
    @Length(min = 0, max = 50)
    private java.lang.String brandsCode;

    /**
     * 品牌名称
     */
    @Length(min = 0, max = 50)
    private java.lang.String brandsName;

    /**
     * 车系代码
     */
    @Length(min = 0, max = 50)
    private java.lang.String seriesCode;

    /**
     * 车系名称
     */
    @Length(min = 0, max = 50)
    private java.lang.String seriesName;

    /**
     * 车型代码
     */
    @Length(min = 0, max = 50)
    private java.lang.String moderCode;

    /**
     * 车型名称
     */
    @Length(min = 0, max = 50)
    private java.lang.String moderName;

    /**
     * 生效时间
     */
    private java.util.Date startTime;

    /**
     * 创建时间
     */
    private java.util.Date createTime;

    /**
     * 修改时间
     */
    private java.util.Date modifyTime;

    /**
     * 创建人
     */
    @Digits(fraction =22,integer=0)
    private Long creator;

    /**
     * 修改人
     */
    @Digits(fraction =22,integer=0)
    private Long modifier;

    /**
     * 所属公司
     */
    @Length(min = 0, max = 20)
    private java.lang.String company;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getActiveReviewId() {
        return this.activeReviewId;
    }

    public void setActiveReviewId(Long activeReviewId) {
        this.activeReviewId = activeReviewId;
    }

    public java.lang.String getActiveCode() {
        return this.activeCode;
    }

    public void setActiveCode(java.lang.String activeCode) {
        this.activeCode = activeCode;
    }

    public Long getSerialNo() {
        return this.serialNo;
    }

    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    public java.lang.String getBrandsCode() {
        return this.brandsCode;
    }

    public void setBrandsCode(java.lang.String brandsCode) {
        this.brandsCode = brandsCode;
    }

    public java.lang.String getBrandsName() {
        return this.brandsName;
    }

    public void setBrandsName(java.lang.String brandsName) {
        this.brandsName = brandsName;
    }

    public java.lang.String getSeriesCode() {
        return this.seriesCode;
    }

    public void setSeriesCode(java.lang.String seriesCode) {
        this.seriesCode = seriesCode;
    }

    public java.lang.String getSeriesName() {
        return this.seriesName;
    }

    public void setSeriesName(java.lang.String seriesName) {
        this.seriesName = seriesName;
    }

    public java.lang.String getModerCode() {
        return this.moderCode;
    }

    public void setModerCode(java.lang.String moderCode) {
        this.moderCode = moderCode;
    }

    public java.lang.String getModerName() {
        return this.moderName;
    }

    public void setModerName(java.lang.String moderName) {
        this.moderName = moderName;
    }

    public java.util.Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public Long getCreator() {
        return this.creator;
    }

    public void setCreator(Long creator) {
        this.creator = creator;
    }

    public Long getModifier() {
        return this.modifier;
    }

    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    public java.lang.String getCompany() {
        return this.company;
    }

    public void setCompany(java.lang.String company) {
        this.company = company;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}