package com.yqjr.fin.risk.stat.entity;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.Digits;

public class A11Dealerdata1 extends BaseEntity<A11Dealerdata1> {

    //region generated by CodeRobot

    private static final long serialVersionUID = 1L;


    /**
     *
     *列表查询页面：/a11Dealerdata1/list
     *表单维护路径：/a11Dealerdata1/form
     *
     */

    /**
     * 库存深度ID
     */
    @Digits(fraction =22,integer=0)
    private Long cid;

    /**
     * 库存深度名称
     */
    @Length(min = 0, max = 100)
    private String cname;

    /**
     * 库存数量
     */
    @Digits(fraction =22,integer=0)
    private Long stock;

    /**
     * 销量
     */
    @Digits(fraction =22,integer=0)
    private Long sales;

    /**
     * 库存深度
     */
    @Digits(fraction =10,integer=6)
    private Long srate;

    /**
     * 品牌名称
     */
    @Length(min = 0, max = 32)
    private String brand;

    /**
     * 该品牌平均库存深度
     */
    @Digits(fraction =22,integer=0)
    private Long brandsrate;

    /**
     * 指标日期
     */
    @Length(min = 0, max = 32)
    private String bizdate;

    public Long getCid() {
        return this.cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    public String getCname() {
        return this.cname;
    }

    public void setCname(String cname) {
        this.cname = cname;
    }

    public Long getStock() {
        return this.stock;
    }

    public void setStock(Long stock) {
        this.stock = stock;
    }

    public Long getSales() {
        return this.sales;
    }

    public void setSales(Long sales) {
        this.sales = sales;
    }

    public Long getSrate() {
        return this.srate;
    }

    public void setSrate(Long srate) {
        this.srate = srate;
    }

    public String getBrand() {
        return this.brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public Long getBrandsrate() {
        return this.brandsrate;
    }

    public void setBrandsrate(Long brandsrate) {
        this.brandsrate = brandsrate;
    }

    public String getBizdate() {
        return this.bizdate;
    }

    public void setBizdate(String bizdate) {
        this.bizdate = bizdate;
    }
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //~此线上方代码自动生成，在此下方编写自定义代码。
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    //endregion
}
