
package com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-06-07T15:04:56.693+08:00
 * Generated source version: 3.1.9
 * 
 */
public final class SelectBillCreateStatusService_SelectBillCreateStatusServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.selectbillcreatestatusimpl.server.expense.yqjr.webservice.cc.epoch.com/", "SelectBillCreateStatusServiceImplService");

    private SelectBillCreateStatusService_SelectBillCreateStatusServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SelectBillCreateStatusServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SelectBillCreateStatusServiceImplService ss = new SelectBillCreateStatusServiceImplService(wsdlURL, SERVICE_NAME);
        SelectBillCreateStatusService port = ss.getSelectBillCreateStatusServiceImplPort();  
        
        {
        System.out.println("Invoking selectBillCreateStatusMethod...");
        com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl.RequestCommon _selectBillCreateStatusMethod_requestCommon = null;
        java.util.List<com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl.BillStatusVO> _selectBillCreateStatusMethod_billStatusList = null;
        try {
            java.util.List<com.yqjr.fin.scfw.isomer.services.cxf.gx.custom.selectbillcreatestatusimpl.BillStatusVO> _selectBillCreateStatusMethod__return = port.selectBillCreateStatusMethod(_selectBillCreateStatusMethod_requestCommon, _selectBillCreateStatusMethod_billStatusList);
            System.out.println("selectBillCreateStatusMethod.result=" + _selectBillCreateStatusMethod__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
